/* LauncherItem.c generated by valac 0.56.16, the Vala compiler
 * generated from LauncherItem.vala, do not modify */

/**/
/* Native application launcher entry point.*/
/**/

#include "plank.h"
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <gee.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <cairo-gobject.h>
#include <float.h>
#include <math.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	PLANK_LAUNCHER_ITEM_0_PROPERTY,
	PLANK_LAUNCHER_ITEM_NUM_PROPERTIES
};
static GParamSpec* plank_launcher_item_properties[PLANK_LAUNCHER_ITEM_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
enum  {
	PLANK_LAUNCHER_PROVIDER_0_PROPERTY,
	PLANK_LAUNCHER_PROVIDER_NUM_PROPERTIES
};
static GParamSpec* plank_launcher_provider_properties[PLANK_LAUNCHER_PROVIDER_NUM_PROPERTIES];

struct _PlankLauncherItemPrivate {
	GdkPixbuf* menu_pixbuf;
};

static gint PlankLauncherItem_private_offset;
static gpointer plank_launcher_item_parent_class = NULL;
static gpointer plank_launcher_provider_parent_class = NULL;

static gboolean plank_launcher_item_real_can_be_removed (PlankDockElement* base);
static void plank_launcher_item_real_draw_icon (PlankDockItem* base,
                                         PlankSurface* surface);
static PlankAnimationType plank_launcher_item_real_on_clicked (PlankDockElement* base,
                                                        PlankPopupButton button,
                                                        GdkModifierType mod,
                                                        guint32 event_time);
static GeeArrayList* plank_launcher_item_real_get_menu_items (PlankDockElement* base);
static void __lambda46_ (PlankLauncherItem* self);
static void ___lambda46__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void plank_launcher_item_finalize (GObject * obj);
static GType plank_launcher_item_get_type_once (void);
static gboolean plank_launcher_provider_real_can_accept_drop (PlankDockElement* base,
                                                       GeeArrayList* uris);
static gboolean plank_launcher_provider_real_move_to (PlankDockContainer* base,
                                               PlankDockElement* move,
                                               PlankDockElement* target);
static GType plank_launcher_provider_get_type_once (void);

static inline gpointer
plank_launcher_item_get_instance_private (PlankLauncherItem* self)
{
	return G_STRUCT_MEMBER_P (self, PlankLauncherItem_private_offset);
}

PlankLauncherItem*
plank_launcher_item_construct (GType object_type)
{
	PlankLauncherItem * self = NULL;
	PlankDockItemPreferences* _tmp0_;
	PlankDockItemPreferences* _tmp1_;
	_tmp0_ = plank_dock_item_preferences_new ();
	_tmp1_ = _tmp0_;
	self = (PlankLauncherItem*) g_object_new (object_type, "Prefs", _tmp1_, "Text", _ ("Applications"), "Icon", "view-app-grid-symbolic", NULL);
	_g_object_unref0 (_tmp1_);
	return self;
}

PlankLauncherItem*
plank_launcher_item_new (void)
{
	return plank_launcher_item_construct (PLANK_TYPE_LAUNCHER_ITEM);
}

static gboolean
plank_launcher_item_real_can_be_removed (PlankDockElement* base)
{
	PlankLauncherItem * self;
	gboolean result;
	self = (PlankLauncherItem*) base;
	result = FALSE;
	return result;
}

static void
plank_launcher_item_real_draw_icon (PlankDockItem* base,
                                    PlankSurface* surface)
{
	PlankLauncherItem * self;
	GdkPixbuf* _tmp0_;
	gint size = 0;
	gint _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	GdkPixbuf* scaled = NULL;
	GdkPixbuf* _tmp10_;
	GdkPixbuf* _tmp11_;
	cairo_t* cr = NULL;
	cairo_t* _tmp12_;
	cairo_t* _tmp13_;
	gdouble x = 0.0;
	gint _tmp14_;
	gint _tmp15_;
	gdouble y = 0.0;
	gint _tmp16_;
	gint _tmp17_;
	gdouble radius = 0.0;
	cairo_t* _tmp18_;
	cairo_t* _tmp19_;
	cairo_t* _tmp20_;
	cairo_t* _tmp21_;
	cairo_t* _tmp22_;
	cairo_t* _tmp23_;
	cairo_t* _tmp24_;
	cairo_t* _tmp25_;
	cairo_t* _tmp26_;
	GdkPixbuf* _tmp27_;
	cairo_t* _tmp28_;
	cairo_t* _tmp29_;
	GError* _inner_error0_ = NULL;
	self = (PlankLauncherItem*) base;
	g_return_if_fail (surface != NULL);
	_tmp0_ = self->priv->menu_pixbuf;
	if (_tmp0_ == NULL) {
		{
			GdkPixbuf* _tmp1_ = NULL;
			GdkPixbuf* _tmp2_;
			GdkPixbuf* _tmp3_;
			_tmp2_ = gdk_pixbuf_new_from_resource (PLANK_G_RESOURCE_PATH "/img/dock-menu.jpg", &_inner_error0_);
			_tmp1_ = _tmp2_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				goto __catch0_g_error;
			}
			_tmp3_ = _tmp1_;
			_tmp1_ = NULL;
			_g_object_unref0 (self->priv->menu_pixbuf);
			self->priv->menu_pixbuf = _tmp3_;
			_g_object_unref0 (_tmp1_);
		}
		goto __finally0;
		__catch0_g_error:
		{
			GError* e = NULL;
			GError* _tmp4_;
			const gchar* _tmp5_;
			e = _inner_error0_;
			_inner_error0_ = NULL;
			_tmp4_ = e;
			_tmp5_ = _tmp4_->message;
			g_warning ("LauncherItem.vala:28: Unable to load dock menu image: %s", _tmp5_);
			_g_error_free0 (e);
			return;
		}
		__finally0:
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
	}
	_tmp6_ = plank_surface_get_Width (surface);
	_tmp7_ = _tmp6_;
	_tmp8_ = plank_surface_get_Height (surface);
	_tmp9_ = _tmp8_;
	size = (gint) (MIN (_tmp7_, _tmp9_) * 0.92);
	_tmp10_ = self->priv->menu_pixbuf;
	_tmp11_ = gdk_pixbuf_scale_simple (_tmp10_, size, size, GDK_INTERP_BILINEAR);
	scaled = _tmp11_;
	_tmp12_ = plank_surface_get_Context (surface);
	_tmp13_ = _tmp12_;
	cr = _tmp13_;
	_tmp14_ = plank_surface_get_Width (surface);
	_tmp15_ = _tmp14_;
	x = (_tmp15_ - size) / 2.0;
	_tmp16_ = plank_surface_get_Height (surface);
	_tmp17_ = _tmp16_;
	y = (_tmp17_ - size) / 2.0;
	radius = size * 0.18;
	_tmp18_ = cr;
	cairo_save (_tmp18_);
	_tmp19_ = cr;
	cairo_new_sub_path (_tmp19_);
	_tmp20_ = cr;
	cairo_arc (_tmp20_, (x + size) - radius, y + radius, radius, -G_PI_2, (gdouble) 0);
	_tmp21_ = cr;
	cairo_arc (_tmp21_, (x + size) - radius, (y + size) - radius, radius, (gdouble) 0, G_PI_2);
	_tmp22_ = cr;
	cairo_arc (_tmp22_, x + radius, (y + size) - radius, radius, G_PI_2, G_PI);
	_tmp23_ = cr;
	cairo_arc (_tmp23_, x + radius, y + radius, radius, G_PI, G_PI * 1.5);
	_tmp24_ = cr;
	cairo_close_path (_tmp24_);
	_tmp25_ = cr;
	cairo_clip (_tmp25_);
	_tmp26_ = cr;
	_tmp27_ = scaled;
	gdk_cairo_set_source_pixbuf (_tmp26_, _tmp27_, x, y);
	_tmp28_ = cr;
	cairo_paint (_tmp28_);
	_tmp29_ = cr;
	cairo_restore (_tmp29_);
	_g_object_unref0 (scaled);
}

static PlankAnimationType
plank_launcher_item_real_on_clicked (PlankDockElement* base,
                                     PlankPopupButton button,
                                     GdkModifierType mod,
                                     guint32 event_time)
{
	PlankLauncherItem * self;
	PlankAnimationType result;
	self = (PlankLauncherItem*) base;
	if (button == PLANK_POPUP_BUTTON_LEFT) {
		PlankDockController* dock = NULL;
		PlankDockController* _tmp0_;
		PlankDockController* _tmp1_;
		_tmp0_ = plank_dock_element_get_dock ((PlankDockElement*) self);
		dock = _tmp0_;
		_tmp1_ = dock;
		if (_tmp1_ != NULL) {
			PlankDockController* _tmp2_;
			PlankLauncherWindow* _tmp3_;
			PlankLauncherWindow* _tmp4_;
			_tmp2_ = dock;
			_tmp3_ = plank_dock_controller_get_launcher (_tmp2_);
			_tmp4_ = _tmp3_;
			plank_launcher_window_toggle (_tmp4_, self);
		}
		result = PLANK_ANIMATION_TYPE_DARKEN;
		return result;
	}
	result = PLANK_ANIMATION_TYPE_NONE;
	return result;
}

static void
__lambda46_ (PlankLauncherItem* self)
{
	PlankDockController* dock = NULL;
	PlankDockController* _tmp0_;
	PlankDockController* _tmp1_;
	_tmp0_ = plank_dock_element_get_dock ((PlankDockElement*) self);
	dock = _tmp0_;
	_tmp1_ = dock;
	if (_tmp1_ != NULL) {
		PlankDockController* _tmp2_;
		PlankLauncherWindow* _tmp3_;
		PlankLauncherWindow* _tmp4_;
		_tmp2_ = dock;
		_tmp3_ = plank_dock_controller_get_launcher (_tmp2_);
		_tmp4_ = _tmp3_;
		plank_launcher_window_show_for_item (_tmp4_, self);
	}
}

static void
___lambda46__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda46_ ((PlankLauncherItem*) self);
}

static GeeArrayList*
plank_launcher_item_real_get_menu_items (PlankDockElement* base)
{
	PlankLauncherItem * self;
	GeeArrayList* items = NULL;
	GeeArrayList* _tmp0_;
	GtkMenuItem* open_item = NULL;
	GtkMenuItem* _tmp1_;
	GeeArrayList* result;
	self = (PlankLauncherItem*) base;
	_tmp0_ = gee_array_list_new (gtk_menu_item_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	items = _tmp0_;
	_tmp1_ = plank_dock_element_create_menu_item (_ ("Open _Applications"), "view-app-grid-symbolic", FALSE);
	open_item = _tmp1_;
	g_signal_connect_object (open_item, "activate", (GCallback) ___lambda46__gtk_menu_item_activate, self, 0);
	gee_abstract_collection_add ((GeeAbstractCollection*) items, open_item);
	result = items;
	_g_object_unref0 (open_item);
	return result;
}

static void
plank_launcher_item_class_init (PlankLauncherItemClass * klass,
                                gpointer klass_data)
{
	plank_launcher_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &PlankLauncherItem_private_offset);
	((PlankDockElementClass *) klass)->can_be_removed = (gboolean (*) (PlankDockElement*)) plank_launcher_item_real_can_be_removed;
	((PlankDockItemClass *) klass)->draw_icon = (void (*) (PlankDockItem*, PlankSurface*)) plank_launcher_item_real_draw_icon;
	((PlankDockElementClass *) klass)->on_clicked = (PlankAnimationType (*) (PlankDockElement*, PlankPopupButton, GdkModifierType, guint32)) plank_launcher_item_real_on_clicked;
	((PlankDockElementClass *) klass)->get_menu_items = (GeeArrayList* (*) (PlankDockElement*)) plank_launcher_item_real_get_menu_items;
	G_OBJECT_CLASS (klass)->finalize = plank_launcher_item_finalize;
}

static void
plank_launcher_item_instance_init (PlankLauncherItem * self,
                                   gpointer klass)
{
	self->priv = plank_launcher_item_get_instance_private (self);
	self->priv->menu_pixbuf = NULL;
}

static void
plank_launcher_item_finalize (GObject * obj)
{
	PlankLauncherItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLANK_TYPE_LAUNCHER_ITEM, PlankLauncherItem);
	_g_object_unref0 (self->priv->menu_pixbuf);
	G_OBJECT_CLASS (plank_launcher_item_parent_class)->finalize (obj);
}

static GType
plank_launcher_item_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PlankLauncherItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) plank_launcher_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlankLauncherItem), 0, (GInstanceInitFunc) plank_launcher_item_instance_init, NULL };
	GType plank_launcher_item_type_id;
	plank_launcher_item_type_id = g_type_register_static (PLANK_TYPE_DOCK_ITEM, "PlankLauncherItem", &g_define_type_info, 0);
	PlankLauncherItem_private_offset = g_type_add_instance_private (plank_launcher_item_type_id, sizeof (PlankLauncherItemPrivate));
	return plank_launcher_item_type_id;
}

GType
plank_launcher_item_get_type (void)
{
	static volatile gsize plank_launcher_item_type_id__once = 0;
	if (g_once_init_enter (&plank_launcher_item_type_id__once)) {
		GType plank_launcher_item_type_id;
		plank_launcher_item_type_id = plank_launcher_item_get_type_once ();
		g_once_init_leave (&plank_launcher_item_type_id__once, plank_launcher_item_type_id);
	}
	return plank_launcher_item_type_id__once;
}

PlankLauncherProvider*
plank_launcher_provider_construct (GType object_type)
{
	PlankLauncherProvider * self = NULL;
	PlankLauncherItem* _tmp0_;
	PlankLauncherItem* _tmp1_;
	self = (PlankLauncherProvider*) g_object_new (object_type, NULL);
	_tmp0_ = plank_launcher_item_new ();
	_tmp1_ = _tmp0_;
	plank_dock_container_add ((PlankDockContainer*) self, (PlankDockElement*) _tmp1_, NULL);
	_g_object_unref0 (_tmp1_);
	return self;
}

PlankLauncherProvider*
plank_launcher_provider_new (void)
{
	return plank_launcher_provider_construct (PLANK_TYPE_LAUNCHER_PROVIDER);
}

static gboolean
plank_launcher_provider_real_can_accept_drop (PlankDockElement* base,
                                              GeeArrayList* uris)
{
	PlankLauncherProvider * self;
	gboolean result;
	self = (PlankLauncherProvider*) base;
	g_return_val_if_fail (uris != NULL, FALSE);
	result = FALSE;
	return result;
}

static gboolean
plank_launcher_provider_real_move_to (PlankDockContainer* base,
                                      PlankDockElement* move,
                                      PlankDockElement* target)
{
	PlankLauncherProvider * self;
	gboolean result;
	self = (PlankLauncherProvider*) base;
	g_return_val_if_fail (move != NULL, FALSE);
	g_return_val_if_fail (target != NULL, FALSE);
	result = FALSE;
	return result;
}

static void
plank_launcher_provider_class_init (PlankLauncherProviderClass * klass,
                                    gpointer klass_data)
{
	plank_launcher_provider_parent_class = g_type_class_peek_parent (klass);
	((PlankDockElementClass *) klass)->can_accept_drop = (gboolean (*) (PlankDockElement*, GeeArrayList*)) plank_launcher_provider_real_can_accept_drop;
	((PlankDockContainerClass *) klass)->move_to = (gboolean (*) (PlankDockContainer*, PlankDockElement*, PlankDockElement*)) plank_launcher_provider_real_move_to;
}

static void
plank_launcher_provider_instance_init (PlankLauncherProvider * self,
                                       gpointer klass)
{
}

static GType
plank_launcher_provider_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PlankLauncherProviderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) plank_launcher_provider_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlankLauncherProvider), 0, (GInstanceInitFunc) plank_launcher_provider_instance_init, NULL };
	GType plank_launcher_provider_type_id;
	plank_launcher_provider_type_id = g_type_register_static (PLANK_TYPE_DOCK_ITEM_PROVIDER, "PlankLauncherProvider", &g_define_type_info, 0);
	return plank_launcher_provider_type_id;
}

GType
plank_launcher_provider_get_type (void)
{
	static volatile gsize plank_launcher_provider_type_id__once = 0;
	if (g_once_init_enter (&plank_launcher_provider_type_id__once)) {
		GType plank_launcher_provider_type_id;
		plank_launcher_provider_type_id = plank_launcher_provider_get_type_once ();
		g_once_init_leave (&plank_launcher_provider_type_id__once, plank_launcher_provider_type_id);
	}
	return plank_launcher_provider_type_id__once;
}

