/* UpdateManagerItem.c generated by valac 0.56.16, the Vala compiler
 * generated from UpdateManagerItem.vala, do not modify */

/* Fixed entry point for the system update manager.*/

#include "plank.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
#include <gee.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>
#include <cairo-gobject.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	PLANK_UPDATE_MANAGER_ITEM_0_PROPERTY,
	PLANK_UPDATE_MANAGER_ITEM_NUM_PROPERTIES
};
static GParamSpec* plank_update_manager_item_properties[PLANK_UPDATE_MANAGER_ITEM_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PlankUpdateManagerItemPrivate {
	gchar* command;
	gboolean updates_available;
	guint update_timer_id;
	guint refresh_debounce_id;
	GFileMonitor* package_monitor;
	GdkPixbuf* update_pixbuf;
};

static gint PlankUpdateManagerItem_private_offset;
static gpointer plank_update_manager_item_parent_class = NULL;

static gboolean plank_update_manager_item_real_can_be_removed (PlankDockElement* base);
static void plank_update_manager_item_check_for_updates (PlankUpdateManagerItem* self);
static void plank_update_manager_item_schedule_immediate_check (PlankUpdateManagerItem* self);
static gboolean __lambda58_ (PlankUpdateManagerItem* self);
static gboolean ___lambda58__gsource_func (gpointer self);
static void plank_update_manager_item_real_draw_icon (PlankDockItem* base,
                                               PlankSurface* surface);
static PlankAnimationType plank_update_manager_item_real_on_hovered (PlankDockElement* base);
static PlankAnimationType plank_update_manager_item_real_on_clicked (PlankDockElement* base,
                                                              PlankPopupButton button,
                                                              GdkModifierType mod,
                                                              guint32 event_time);
static void plank_update_manager_item_launch (PlankUpdateManagerItem* self);
static void ___lambda59_ (PlankUpdateManagerItem* self,
                   GPid child_pid,
                   gint status);
static void ____lambda59__gchild_watch_func (GPid pid,
                                      gint wait_status,
                                      gpointer self);
static GeeArrayList* plank_update_manager_item_real_get_menu_items (PlankDockElement* base);
static void _plank_update_manager_item_launch_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                               gpointer self);
static GObject * plank_update_manager_item_constructor (GType type,
                                                 guint n_construct_properties,
                                                 GObjectConstructParam * construct_properties);
static gboolean _plank_update_manager_item___lambda60_ (PlankUpdateManagerItem* self);
static gboolean __plank_update_manager_item___lambda60__gsource_func (gpointer self);
static gboolean _plank_update_manager_item___lambda61_ (PlankUpdateManagerItem* self);
static gboolean __plank_update_manager_item___lambda61__gsource_func (gpointer self);
static void _plank_update_manager_item____lambda62_ (PlankUpdateManagerItem* self);
static void __plank_update_manager_item____lambda62__g_file_monitor_changed (GFileMonitor* _sender,
                                                                      GFile* file,
                                                                      GFile* other_file,
                                                                      GFileMonitorEvent event_type,
                                                                      gpointer self);
static void plank_update_manager_item_finalize (GObject * obj);
static GType plank_update_manager_item_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
plank_update_manager_item_get_instance_private (PlankUpdateManagerItem* self)
{
	return G_STRUCT_MEMBER_P (self, PlankUpdateManagerItem_private_offset);
}

PlankUpdateManagerItem*
plank_update_manager_item_construct (GType object_type,
                                     const gchar* command)
{
	PlankUpdateManagerItem * self = NULL;
	PlankDockItemPreferences* _tmp0_;
	PlankDockItemPreferences* _tmp1_;
	gchar* _tmp2_;
	g_return_val_if_fail (command != NULL, NULL);
	_tmp0_ = plank_dock_item_preferences_new ();
	_tmp1_ = _tmp0_;
	self = (PlankUpdateManagerItem*) g_object_new (object_type, "Prefs", _tmp1_, "Text", _ ("Update Manager"), "Icon", "software-update-available-symbolic", NULL);
	_g_object_unref0 (_tmp1_);
	_tmp2_ = g_strdup (command);
	_g_free0 (self->priv->command);
	self->priv->command = _tmp2_;
	return self;
}

PlankUpdateManagerItem*
plank_update_manager_item_new (const gchar* command)
{
	return plank_update_manager_item_construct (PLANK_TYPE_UPDATE_MANAGER_ITEM, command);
}

gchar*
plank_update_manager_item_available_command (void)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gboolean _tmp6_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gboolean _tmp10_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gboolean _tmp14_;
	gchar* result;
	_tmp0_ = g_find_program_in_path ("mintupdate");
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_ != NULL;
	_g_free0 (_tmp1_);
	if (_tmp2_) {
		gchar* _tmp3_;
		_tmp3_ = g_strdup ("mintupdate");
		result = _tmp3_;
		return result;
	}
	_tmp4_ = g_find_program_in_path ("update-manager");
	_tmp5_ = _tmp4_;
	_tmp6_ = _tmp5_ != NULL;
	_g_free0 (_tmp5_);
	if (_tmp6_) {
		gchar* _tmp7_;
		_tmp7_ = g_strdup ("update-manager");
		result = _tmp7_;
		return result;
	}
	_tmp8_ = g_find_program_in_path ("gnome-software");
	_tmp9_ = _tmp8_;
	_tmp10_ = _tmp9_ != NULL;
	_g_free0 (_tmp9_);
	if (_tmp10_) {
		gchar* _tmp11_;
		_tmp11_ = g_strdup ("gnome-software --mode=updates");
		result = _tmp11_;
		return result;
	}
	_tmp12_ = g_find_program_in_path ("plasma-discover");
	_tmp13_ = _tmp12_;
	_tmp14_ = _tmp13_ != NULL;
	_g_free0 (_tmp13_);
	if (_tmp14_) {
		gchar* _tmp15_;
		_tmp15_ = g_strdup ("plasma-discover --mode update");
		result = _tmp15_;
		return result;
	}
	result = NULL;
	return result;
}

static gboolean
plank_update_manager_item_real_can_be_removed (PlankDockElement* base)
{
	PlankUpdateManagerItem * self;
	gboolean result;
	self = (PlankUpdateManagerItem*) base;
	result = FALSE;
	return result;
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
	result = _tmp0_ != NULL;
	return result;
}

static void
plank_update_manager_item_check_for_updates (PlankUpdateManagerItem* self)
{
	gchar* output = NULL;
	gchar* _tmp0_;
	gchar* error_output = NULL;
	gchar* _tmp1_;
	gint status = 0;
	gboolean _tmp20_ = FALSE;
	gboolean available = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	output = _tmp0_;
	_tmp1_ = g_strdup ("");
	error_output = _tmp1_;
	status = 1;
	{
		gchar* _tmp2_;
		gchar* _tmp3_;
		gboolean _tmp4_;
		_tmp2_ = g_find_program_in_path ("mintupdate-cli");
		_tmp3_ = _tmp2_;
		_tmp4_ = _tmp3_ != NULL;
		_g_free0 (_tmp3_);
		if (_tmp4_) {
			gchar* _tmp5_ = NULL;
			gchar* _tmp6_ = NULL;
			gint _tmp7_ = 0;
			g_spawn_command_line_sync ("mintupdate-cli list", &_tmp5_, &_tmp6_, &_tmp7_, &_inner_error0_);
			_g_free0 (output);
			output = _tmp5_;
			_g_free0 (error_output);
			error_output = _tmp6_;
			status = _tmp7_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				if (_inner_error0_->domain == G_SPAWN_ERROR) {
					goto __catch0_g_spawn_error;
				}
				_g_free0 (error_output);
				_g_free0 (output);
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
				g_clear_error (&_inner_error0_);
				return;
			}
		} else {
			gchar* _tmp8_;
			gchar* _tmp9_;
			gboolean _tmp10_;
			_tmp8_ = g_find_program_in_path ("apt");
			_tmp9_ = _tmp8_;
			_tmp10_ = _tmp9_ != NULL;
			_g_free0 (_tmp9_);
			if (_tmp10_) {
				gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				gint _tmp13_ = 0;
				g_spawn_command_line_sync ("apt list --upgradable", &_tmp11_, &_tmp12_, &_tmp13_, &_inner_error0_);
				_g_free0 (output);
				output = _tmp11_;
				_g_free0 (error_output);
				error_output = _tmp12_;
				status = _tmp13_;
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					if (_inner_error0_->domain == G_SPAWN_ERROR) {
						goto __catch0_g_spawn_error;
					}
					_g_free0 (error_output);
					_g_free0 (output);
					g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
					g_clear_error (&_inner_error0_);
					return;
				}
			} else {
				gchar* _tmp14_;
				gchar* _tmp15_;
				gboolean _tmp16_;
				_tmp14_ = g_find_program_in_path ("pkcon");
				_tmp15_ = _tmp14_;
				_tmp16_ = _tmp15_ != NULL;
				_g_free0 (_tmp15_);
				if (_tmp16_) {
					gchar* _tmp17_ = NULL;
					gchar* _tmp18_ = NULL;
					gint _tmp19_ = 0;
					g_spawn_command_line_sync ("pkcon get-updates", &_tmp17_, &_tmp18_, &_tmp19_, &_inner_error0_);
					_g_free0 (output);
					output = _tmp17_;
					_g_free0 (error_output);
					error_output = _tmp18_;
					status = _tmp19_;
					if (G_UNLIKELY (_inner_error0_ != NULL)) {
						if (_inner_error0_->domain == G_SPAWN_ERROR) {
							goto __catch0_g_spawn_error;
						}
						_g_free0 (error_output);
						_g_free0 (output);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
						g_clear_error (&_inner_error0_);
						return;
					}
				}
			}
		}
	}
	goto __finally0;
	__catch0_g_spawn_error:
	{
		g_clear_error (&_inner_error0_);
		status = 1;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (error_output);
		_g_free0 (output);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	if (status == 0) {
		gboolean _tmp21_ = FALSE;
		gboolean _tmp22_ = FALSE;
		const gchar* _tmp23_;
		_tmp23_ = output;
		if (string_contains (_tmp23_, "package         ")) {
			_tmp22_ = TRUE;
		} else {
			const gchar* _tmp24_;
			_tmp24_ = output;
			_tmp22_ = string_contains (_tmp24_, "[upgradable from:");
		}
		if (_tmp22_) {
			_tmp21_ = TRUE;
		} else {
			const gchar* _tmp25_;
			_tmp25_ = output;
			_tmp21_ = string_contains (_tmp25_, "Available");
		}
		_tmp20_ = _tmp21_;
	} else {
		_tmp20_ = FALSE;
	}
	available = _tmp20_;
	if (available != self->priv->updates_available) {
		self->priv->updates_available = available;
		plank_dock_item_reset_icon_buffer ((PlankDockItem*) self);
	}
	_g_free0 (error_output);
	_g_free0 (output);
}

static gboolean
__lambda58_ (PlankUpdateManagerItem* self)
{
	gboolean result;
	self->priv->refresh_debounce_id = 0U;
	plank_update_manager_item_check_for_updates (self);
	result = FALSE;
	return result;
}

static gboolean
___lambda58__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda58_ ((PlankUpdateManagerItem*) self);
	return result;
}

static void
plank_update_manager_item_schedule_immediate_check (PlankUpdateManagerItem* self)
{
	g_return_if_fail (self != NULL);
	if (self->priv->refresh_debounce_id > 0U) {
		g_source_remove (self->priv->refresh_debounce_id);
	}
	self->priv->refresh_debounce_id = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 2, ___lambda58__gsource_func, g_object_ref (self), g_object_unref);
}

static void
plank_update_manager_item_real_draw_icon (PlankDockItem* base,
                                          PlankSurface* surface)
{
	PlankUpdateManagerItem * self;
	gdouble size = 0.0;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint icon_size = 0;
	GError* _inner_error0_ = NULL;
	self = (PlankUpdateManagerItem*) base;
	g_return_if_fail (surface != NULL);
	_tmp0_ = plank_surface_get_Width (surface);
	_tmp1_ = _tmp0_;
	_tmp2_ = plank_surface_get_Height (surface);
	_tmp3_ = _tmp2_;
	size = MIN ((gdouble) _tmp1_, (gdouble) _tmp3_);
	icon_size = (gint) (size * 0.54);
	{
		GdkPixbuf* _tmp4_;
		cairo_t* cr = NULL;
		cairo_t* _tmp8_;
		cairo_t* _tmp9_;
		cairo_t* _tmp10_;
		GdkPixbuf* _tmp11_;
		gint _tmp12_;
		gint _tmp13_;
		GdkPixbuf* _tmp14_;
		gint _tmp15_;
		gint _tmp16_;
		gint _tmp17_;
		gint _tmp18_;
		GdkPixbuf* _tmp19_;
		gint _tmp20_;
		gint _tmp21_;
		cairo_t* _tmp22_;
		_tmp4_ = self->priv->update_pixbuf;
		if (_tmp4_ == NULL) {
			GdkPixbuf* _tmp5_ = NULL;
			GdkPixbuf* _tmp6_;
			GdkPixbuf* _tmp7_;
			_tmp6_ = gdk_pixbuf_new_from_resource_at_scale (PLANK_G_RESOURCE_PATH "/lucide/refresh-cw.svg", icon_size, icon_size, TRUE, &_inner_error0_);
			_tmp5_ = _tmp6_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				goto __catch0_g_error;
			}
			_tmp7_ = _tmp5_;
			_tmp5_ = NULL;
			_g_object_unref0 (self->priv->update_pixbuf);
			self->priv->update_pixbuf = _tmp7_;
			_g_object_unref0 (_tmp5_);
		}
		_tmp8_ = plank_surface_get_Context (surface);
		_tmp9_ = _tmp8_;
		cr = _tmp9_;
		_tmp10_ = cr;
		_tmp11_ = self->priv->update_pixbuf;
		_tmp12_ = plank_surface_get_Width (surface);
		_tmp13_ = _tmp12_;
		_tmp14_ = self->priv->update_pixbuf;
		_tmp15_ = gdk_pixbuf_get_width (_tmp14_);
		_tmp16_ = _tmp15_;
		_tmp17_ = plank_surface_get_Height (surface);
		_tmp18_ = _tmp17_;
		_tmp19_ = self->priv->update_pixbuf;
		_tmp20_ = gdk_pixbuf_get_height (_tmp19_);
		_tmp21_ = _tmp20_;
		gdk_cairo_set_source_pixbuf (_tmp10_, _tmp11_, (_tmp13_ - _tmp16_) / 2.0, (_tmp18_ - _tmp21_) / 2.0);
		_tmp22_ = cr;
		cairo_paint_with_alpha (_tmp22_, 0.92);
		if (self->priv->updates_available) {
			gdouble cx = 0.0;
			gint _tmp23_;
			gint _tmp24_;
			gdouble cy = 0.0;
			gint _tmp25_;
			gint _tmp26_;
			gdouble radius = 0.0;
			cairo_t* _tmp27_;
			cairo_t* _tmp28_;
			cairo_t* _tmp29_;
			cairo_t* _tmp30_;
			cairo_t* _tmp31_;
			cairo_t* _tmp32_;
			_tmp23_ = plank_surface_get_Width (surface);
			_tmp24_ = _tmp23_;
			cx = _tmp24_ * 0.70;
			_tmp25_ = plank_surface_get_Height (surface);
			_tmp26_ = _tmp25_;
			cy = _tmp26_ * 0.28;
			radius = size * 0.075;
			_tmp27_ = cr;
			cairo_set_source_rgba (_tmp27_, 0.10, 0.14, 0.10, 0.95);
			_tmp28_ = cr;
			cairo_arc (_tmp28_, cx, cy, radius + (size * 0.025), (gdouble) 0, G_PI * 2.0);
			_tmp29_ = cr;
			cairo_fill (_tmp29_);
			_tmp30_ = cr;
			cairo_set_source_rgba (_tmp30_, 0.45, 0.82, 0.09, 1.0);
			_tmp31_ = cr;
			cairo_arc (_tmp31_, cx, cy, radius, (gdouble) 0, G_PI * 2.0);
			_tmp32_ = cr;
			cairo_fill (_tmp32_);
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp33_;
		const gchar* _tmp34_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp33_ = e;
		_tmp34_ = _tmp33_->message;
		g_warning ("UpdateManagerItem.vala:124: Unable to load update icon: %s", _tmp34_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

static PlankAnimationType
plank_update_manager_item_real_on_hovered (PlankDockElement* base)
{
	PlankUpdateManagerItem * self;
	PlankAnimationType result;
	self = (PlankUpdateManagerItem*) base;
	result = PLANK_ANIMATION_TYPE_LIGHTEN;
	return result;
}

static PlankAnimationType
plank_update_manager_item_real_on_clicked (PlankDockElement* base,
                                           PlankPopupButton button,
                                           GdkModifierType mod,
                                           guint32 event_time)
{
	PlankUpdateManagerItem * self;
	PlankAnimationType result;
	self = (PlankUpdateManagerItem*) base;
	if (button == PLANK_POPUP_BUTTON_LEFT) {
		plank_update_manager_item_launch (self);
		result = PLANK_ANIMATION_TYPE_DARKEN;
		return result;
	}
	result = PLANK_ANIMATION_TYPE_NONE;
	return result;
}

static void
___lambda59_ (PlankUpdateManagerItem* self,
              GPid child_pid,
              gint status)
{
	g_spawn_close_pid (child_pid);
	plank_update_manager_item_schedule_immediate_check (self);
}

static void
____lambda59__gchild_watch_func (GPid pid,
                                 gint wait_status,
                                 gpointer self)
{
	___lambda59_ ((PlankUpdateManagerItem*) self, pid, wait_status);
}

static void
plank_update_manager_item_launch (PlankUpdateManagerItem* self)
{
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	{
		gchar** arguments = NULL;
		gint arguments_length1 = 0;
		gint _arguments_size_ = 0;
		const gchar* _tmp0_;
		gchar** _tmp1_ = NULL;
		gint _tmp2_ = 0;
		GPid pid = 0;
		gchar** _tmp3_;
		gint _tmp3__length1;
		GPid _tmp4_ = 0;
		_tmp0_ = self->priv->command;
		g_shell_parse_argv (_tmp0_, &_tmp2_, &_tmp1_, &_inner_error0_);
		arguments = (_vala_array_free (arguments, arguments_length1, (GDestroyNotify) g_free), NULL);
		arguments = _tmp1_;
		arguments_length1 = _tmp2_;
		_arguments_size_ = arguments_length1;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			arguments = (_vala_array_free (arguments, arguments_length1, (GDestroyNotify) g_free), NULL);
			goto __catch0_g_error;
		}
		_tmp3_ = arguments;
		_tmp3__length1 = arguments_length1;
		g_spawn_async (NULL, _tmp3_, NULL, G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp4_, &_inner_error0_);
		pid = _tmp4_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			arguments = (_vala_array_free (arguments, arguments_length1, (GDestroyNotify) g_free), NULL);
			goto __catch0_g_error;
		}
		g_child_watch_add_full (G_PRIORITY_DEFAULT_IDLE, pid, ____lambda59__gchild_watch_func, g_object_ref (self), g_object_unref);
		arguments = (_vala_array_free (arguments, arguments_length1, (GDestroyNotify) g_free), NULL);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp5_;
		const gchar* _tmp6_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		g_warning ("UpdateManagerItem.vala:156: Unable to open update manager: %s", _tmp6_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

static void
_plank_update_manager_item_launch_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                          gpointer self)
{
	plank_update_manager_item_launch ((PlankUpdateManagerItem*) self);
}

static GeeArrayList*
plank_update_manager_item_real_get_menu_items (PlankDockElement* base)
{
	PlankUpdateManagerItem * self;
	GeeArrayList* items = NULL;
	GeeArrayList* _tmp0_;
	GtkMenuItem* open = NULL;
	GtkMenuItem* _tmp1_;
	GeeArrayList* result;
	self = (PlankUpdateManagerItem*) base;
	_tmp0_ = gee_array_list_new (gtk_menu_item_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	items = _tmp0_;
	_tmp1_ = plank_dock_element_create_menu_item (_ ("Open _Update Manager"), "software-update-available-symbolic", FALSE);
	open = _tmp1_;
	g_signal_connect_object (open, "activate", (GCallback) _plank_update_manager_item_launch_gtk_menu_item_activate, self, 0);
	gee_abstract_collection_add ((GeeAbstractCollection*) items, open);
	result = items;
	_g_object_unref0 (open);
	return result;
}

static gboolean
_plank_update_manager_item___lambda60_ (PlankUpdateManagerItem* self)
{
	gboolean result;
	plank_update_manager_item_check_for_updates (self);
	result = FALSE;
	return result;
}

static gboolean
__plank_update_manager_item___lambda60__gsource_func (gpointer self)
{
	gboolean result;
	result = _plank_update_manager_item___lambda60_ ((PlankUpdateManagerItem*) self);
	return result;
}

static gboolean
_plank_update_manager_item___lambda61_ (PlankUpdateManagerItem* self)
{
	gboolean result;
	plank_update_manager_item_check_for_updates (self);
	result = TRUE;
	return result;
}

static gboolean
__plank_update_manager_item___lambda61__gsource_func (gpointer self)
{
	gboolean result;
	result = _plank_update_manager_item___lambda61_ ((PlankUpdateManagerItem*) self);
	return result;
}

static void
_plank_update_manager_item____lambda62_ (PlankUpdateManagerItem* self)
{
	plank_update_manager_item_schedule_immediate_check (self);
}

static void
__plank_update_manager_item____lambda62__g_file_monitor_changed (GFileMonitor* _sender,
                                                                 GFile* file,
                                                                 GFile* other_file,
                                                                 GFileMonitorEvent event_type,
                                                                 gpointer self)
{
	_plank_update_manager_item____lambda62_ ((PlankUpdateManagerItem*) self);
}

static GObject *
plank_update_manager_item_constructor (GType type,
                                       guint n_construct_properties,
                                       GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	PlankUpdateManagerItem * self;
	GError* _inner_error0_ = NULL;
	parent_class = G_OBJECT_CLASS (plank_update_manager_item_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLANK_TYPE_UPDATE_MANAGER_ITEM, PlankUpdateManagerItem);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, __plank_update_manager_item___lambda60__gsource_func, g_object_ref (self), g_object_unref);
	self->priv->update_timer_id = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 300, __plank_update_manager_item___lambda61__gsource_func, g_object_ref (self), g_object_unref);
	{
		GFileMonitor* _tmp0_ = NULL;
		GFile* _tmp1_;
		GFile* _tmp2_;
		GFileMonitor* _tmp3_;
		GFileMonitor* _tmp4_;
		GFileMonitor* _tmp5_;
		GFileMonitor* _tmp6_;
		_tmp1_ = g_file_new_for_path ("/var/lib/dpkg/status");
		_tmp2_ = _tmp1_;
		_tmp3_ = g_file_monitor_file (_tmp2_, G_FILE_MONITOR_NONE, NULL, &_inner_error0_);
		_tmp4_ = _tmp3_;
		_g_object_unref0 (_tmp2_);
		_tmp0_ = _tmp4_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp5_ = _tmp0_;
		_tmp0_ = NULL;
		_g_object_unref0 (self->priv->package_monitor);
		self->priv->package_monitor = _tmp5_;
		_tmp6_ = self->priv->package_monitor;
		g_signal_connect_object (_tmp6_, "changed", (GCallback) __plank_update_manager_item____lambda62__g_file_monitor_changed, self, 0);
		_g_object_unref0 (_tmp0_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		g_clear_error (&_inner_error0_);
		_g_object_unref0 (self->priv->package_monitor);
		self->priv->package_monitor = NULL;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
	}
	return obj;
}

static void
plank_update_manager_item_class_init (PlankUpdateManagerItemClass * klass,
                                      gpointer klass_data)
{
	plank_update_manager_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &PlankUpdateManagerItem_private_offset);
	((PlankDockElementClass *) klass)->can_be_removed = (gboolean (*) (PlankDockElement*)) plank_update_manager_item_real_can_be_removed;
	((PlankDockItemClass *) klass)->draw_icon = (void (*) (PlankDockItem*, PlankSurface*)) plank_update_manager_item_real_draw_icon;
	((PlankDockElementClass *) klass)->on_hovered = (PlankAnimationType (*) (PlankDockElement*)) plank_update_manager_item_real_on_hovered;
	((PlankDockElementClass *) klass)->on_clicked = (PlankAnimationType (*) (PlankDockElement*, PlankPopupButton, GdkModifierType, guint32)) plank_update_manager_item_real_on_clicked;
	((PlankDockElementClass *) klass)->get_menu_items = (GeeArrayList* (*) (PlankDockElement*)) plank_update_manager_item_real_get_menu_items;
	G_OBJECT_CLASS (klass)->constructor = plank_update_manager_item_constructor;
	G_OBJECT_CLASS (klass)->finalize = plank_update_manager_item_finalize;
}

static void
plank_update_manager_item_instance_init (PlankUpdateManagerItem * self,
                                         gpointer klass)
{
	self->priv = plank_update_manager_item_get_instance_private (self);
	self->priv->updates_available = FALSE;
	self->priv->update_timer_id = 0U;
	self->priv->refresh_debounce_id = 0U;
}

static void
plank_update_manager_item_finalize (GObject * obj)
{
	PlankUpdateManagerItem * self;
	GFileMonitor* _tmp0_;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLANK_TYPE_UPDATE_MANAGER_ITEM, PlankUpdateManagerItem);
	if (self->priv->update_timer_id > 0U) {
		g_source_remove (self->priv->update_timer_id);
	}
	if (self->priv->refresh_debounce_id > 0U) {
		g_source_remove (self->priv->refresh_debounce_id);
	}
	_tmp0_ = self->priv->package_monitor;
	if (_tmp0_ != NULL) {
		GFileMonitor* _tmp1_;
		_tmp1_ = self->priv->package_monitor;
		g_file_monitor_cancel (_tmp1_);
	}
	_g_free0 (self->priv->command);
	_g_object_unref0 (self->priv->package_monitor);
	_g_object_unref0 (self->priv->update_pixbuf);
	G_OBJECT_CLASS (plank_update_manager_item_parent_class)->finalize (obj);
}

static GType
plank_update_manager_item_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PlankUpdateManagerItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) plank_update_manager_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlankUpdateManagerItem), 0, (GInstanceInitFunc) plank_update_manager_item_instance_init, NULL };
	GType plank_update_manager_item_type_id;
	plank_update_manager_item_type_id = g_type_register_static (PLANK_TYPE_DOCK_ITEM, "PlankUpdateManagerItem", &g_define_type_info, 0);
	PlankUpdateManagerItem_private_offset = g_type_add_instance_private (plank_update_manager_item_type_id, sizeof (PlankUpdateManagerItemPrivate));
	return plank_update_manager_item_type_id;
}

GType
plank_update_manager_item_get_type (void)
{
	static volatile gsize plank_update_manager_item_type_id__once = 0;
	if (g_once_init_enter (&plank_update_manager_item_type_id__once)) {
		GType plank_update_manager_item_type_id;
		plank_update_manager_item_type_id = plank_update_manager_item_get_type_once ();
		g_once_init_leave (&plank_update_manager_item_type_id__once, plank_update_manager_item_type_id);
	}
	return plank_update_manager_item_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

