/* TestHelper.c generated by valac 0.56.16, the Vala compiler
 * generated from TestHelper.vala, do not modify */

/**/
/*  Copyright (C) 2015 Rico Tzschichholz*/
/**/
/*  This file is part of Plank.*/
/**/
/*  Plank is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  Plank is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include "plank.h"
#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define PLANK_TESTS_TYPE_TEST_DOCK_ITEM (plank_tests_test_dock_item_get_type ())
#define PLANK_TESTS_TEST_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLANK_TESTS_TYPE_TEST_DOCK_ITEM, PlankTestsTestDockItem))
#define PLANK_TESTS_TEST_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLANK_TESTS_TYPE_TEST_DOCK_ITEM, PlankTestsTestDockItemClass))
#define PLANK_TESTS_IS_TEST_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLANK_TESTS_TYPE_TEST_DOCK_ITEM))
#define PLANK_TESTS_IS_TEST_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLANK_TESTS_TYPE_TEST_DOCK_ITEM))
#define PLANK_TESTS_TEST_DOCK_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLANK_TESTS_TYPE_TEST_DOCK_ITEM, PlankTestsTestDockItemClass))

typedef struct _PlankTestsTestDockItem PlankTestsTestDockItem;
typedef struct _PlankTestsTestDockItemClass PlankTestsTestDockItemClass;
typedef struct _PlankTestsTestDockItemPrivate PlankTestsTestDockItemPrivate;
enum  {
	PLANK_TESTS_TEST_DOCK_ITEM_0_PROPERTY,
	PLANK_TESTS_TEST_DOCK_ITEM_NUM_PROPERTIES
};
static GParamSpec* plank_tests_test_dock_item_properties[PLANK_TESTS_TEST_DOCK_ITEM_NUM_PROPERTIES];

struct _PlankTestsTestDockItem {
	PlankDockItem parent_instance;
	PlankTestsTestDockItemPrivate * priv;
};

struct _PlankTestsTestDockItemClass {
	PlankDockItemClass parent_class;
};

static gpointer plank_tests_test_dock_item_parent_class = NULL;

VALA_EXTERN GType plank_tests_test_dock_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PlankTestsTestDockItem, g_object_unref)
VALA_EXTERN PlankTestsTestDockItem* plank_tests_test_dock_item_new (void);
VALA_EXTERN PlankTestsTestDockItem* plank_tests_test_dock_item_construct (GType object_type);
static GType plank_tests_test_dock_item_get_type_once (void);
VALA_EXTERN gboolean plank_tests_pixbuf_equal (GdkPixbuf* p1,
                                   GdkPixbuf* p2);

PlankTestsTestDockItem*
plank_tests_test_dock_item_construct (GType object_type)
{
	PlankTestsTestDockItem * self = NULL;
	self = (PlankTestsTestDockItem*) plank_dock_item_construct (object_type);
	return self;
}

PlankTestsTestDockItem*
plank_tests_test_dock_item_new (void)
{
	return plank_tests_test_dock_item_construct (PLANK_TESTS_TYPE_TEST_DOCK_ITEM);
}

static void
plank_tests_test_dock_item_class_init (PlankTestsTestDockItemClass * klass,
                                       gpointer klass_data)
{
	plank_tests_test_dock_item_parent_class = g_type_class_peek_parent (klass);
}

static void
plank_tests_test_dock_item_instance_init (PlankTestsTestDockItem * self,
                                          gpointer klass)
{
}

static GType
plank_tests_test_dock_item_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PlankTestsTestDockItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) plank_tests_test_dock_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlankTestsTestDockItem), 0, (GInstanceInitFunc) plank_tests_test_dock_item_instance_init, NULL };
	GType plank_tests_test_dock_item_type_id;
	plank_tests_test_dock_item_type_id = g_type_register_static (PLANK_TYPE_DOCK_ITEM, "PlankTestsTestDockItem", &g_define_type_info, 0);
	return plank_tests_test_dock_item_type_id;
}

GType
plank_tests_test_dock_item_get_type (void)
{
	static volatile gsize plank_tests_test_dock_item_type_id__once = 0;
	if (g_once_init_enter (&plank_tests_test_dock_item_type_id__once)) {
		GType plank_tests_test_dock_item_type_id;
		plank_tests_test_dock_item_type_id = plank_tests_test_dock_item_get_type_once ();
		g_once_init_leave (&plank_tests_test_dock_item_type_id__once, plank_tests_test_dock_item_type_id);
	}
	return plank_tests_test_dock_item_type_id__once;
}

gboolean
plank_tests_pixbuf_equal (GdkPixbuf* p1,
                          GdkPixbuf* p2)
{
	guint8* _tmp0_;
	guint8* _tmp1_;
	gboolean result;
	g_return_val_if_fail (p1 != NULL, FALSE);
	g_return_val_if_fail (p2 != NULL, FALSE);
	if (gdk_pixbuf_get_colorspace (p1) != gdk_pixbuf_get_colorspace (p2)) {
		result = FALSE;
		return result;
	}
	if (gdk_pixbuf_get_n_channels (p1) != gdk_pixbuf_get_n_channels (p2)) {
		result = FALSE;
		return result;
	}
	if (gdk_pixbuf_get_bits_per_sample (p1) != gdk_pixbuf_get_bits_per_sample (p2)) {
		result = FALSE;
		return result;
	}
	if (gdk_pixbuf_get_width (p1) != gdk_pixbuf_get_width (p2)) {
		result = FALSE;
		return result;
	}
	if (gdk_pixbuf_get_height (p1) != gdk_pixbuf_get_height (p2)) {
		result = FALSE;
		return result;
	}
	if (gdk_pixbuf_get_rowstride (p1) != gdk_pixbuf_get_rowstride (p2)) {
		result = FALSE;
		return result;
	}
	_tmp0_ = gdk_pixbuf_get_pixels (p1);
	_tmp1_ = gdk_pixbuf_get_pixels (p2);
	if (memcmp ((void*) _tmp0_, (void*) _tmp1_, gdk_pixbuf_get_byte_length (p1)) != 0) {
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}

