/* StatusPanelWindow.c generated by valac 0.56.16, the Vala compiler
 * generated from StatusPanelWindow.vala, do not modify */

/* Native reusable panel for the fixed system indicators.*/

#include "plank.h"
#include <gtk/gtk.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <glib-object.h>
#include <cairo-gobject.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <pango/pango.h>
#include <glib/gstdio.h>

#define PLANK_STATUS_PANEL_WINDOW_PANEL_WIDTH 245
#define PLANK_STATUS_PANEL_WINDOW_PANEL_HEIGHT 400
#define PLANK_STATUS_PANEL_WINDOW_VOLUME_PANEL_SIZE 300
#define PLANK_STATUS_PANEL_WINDOW_PANEL_GAP 10
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	PLANK_STATUS_PANEL_WINDOW_0_PROPERTY,
	PLANK_STATUS_PANEL_WINDOW_NUM_PROPERTIES
};
static GParamSpec* plank_status_panel_window_properties[PLANK_STATUS_PANEL_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block27Data Block27Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block28Data Block28Data;
typedef struct _Block29Data Block29Data;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef void (*PlankStatusPanelWindowSwitchChanged) (gboolean state, gpointer user_data);
#define _g_dir_close0(var) ((var == NULL) ? NULL : (var = (g_dir_close (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
typedef struct _Block30Data Block30Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PlankStatusPanelWindowPrivate {
	PlankDockController* controller;
	GtkBox* content;
	GtkBox* footer;
	PlankStatusIndicatorItem* current_item;
	GtkCssProvider* css_provider;
	gint active_panel_width;
	gint active_panel_height;
	gboolean device_popup_open;
};

struct _Block27Data {
	int _ref_count_;
	PlankStatusPanelWindow* self;
	PlankDockController* controller;
};

struct _Block28Data {
	int _ref_count_;
	PlankStatusPanelWindow* self;
	GtkScale* scale;
	GtkToggleButton* icon;
	GtkLabel* value;
	gchar* target;
};

struct _Block29Data {
	int _ref_count_;
	PlankStatusPanelWindow* self;
	GtkComboBoxText* combo;
	gboolean source;
};

struct _Block30Data {
	int _ref_count_;
	PlankStatusPanelWindow* self;
	GtkSwitch* toggle;
	PlankStatusPanelWindowSwitchChanged changed;
	gpointer changed_target;
	GDestroyNotify changed_target_destroy_notify;
};

static gint PlankStatusPanelWindow_private_offset;
static gpointer plank_status_panel_window_parent_class = NULL;

static Block27Data* block27_data_ref (Block27Data* _data27_);
static void block27_data_unref (void * _userdata_);
static gboolean __lambda29_ (PlankStatusPanelWindow* self);
static gboolean ___lambda29__gtk_widget_focus_out_event (GtkWidget* _sender,
                                                  GdkEventFocus* event,
                                                  gpointer self);
static void __lambda30_ (Block27Data* _data27_);
static void ___lambda30__gtk_widget_show (GtkWidget* _sender,
                                   gpointer self);
static void __lambda64_ (Block27Data* _data27_);
static void ___lambda64__gtk_widget_hide (GtkWidget* _sender,
                                   gpointer self);
static void plank_status_panel_window_apply_geometry (PlankStatusPanelWindow* self,
                                               PlankStatusIndicatorKind kind);
static void plank_status_panel_window_rebuild (PlankStatusPanelWindow* self,
                                        PlankStatusIndicatorKind kind);
static void plank_status_panel_window_apply_theme (PlankStatusPanelWindow* self);
static gboolean __lambda74_ (PlankStatusPanelWindow* self);
static void plank_status_panel_window_position_over_item (PlankStatusPanelWindow* self);
static gboolean __lambda75_ (PlankStatusPanelWindow* self);
static gboolean ___lambda75__gsource_func (gpointer self);
static gboolean ___lambda74__gsource_func (gpointer self);
static void plank_status_panel_window_active_workarea (PlankStatusPanelWindow* self,
                                                GdkRectangle* result);
static GtkWidget* plank_status_panel_window_title_row (PlankStatusPanelWindow* self,
                                                const gchar* title,
                                                const gchar* icon);
static gchar* plank_status_panel_window_label_for_kind (PlankStatusIndicatorKind kind);
static gchar* plank_status_panel_window_icon_for_kind (PlankStatusIndicatorKind kind);
static void plank_status_panel_window_build_volume (PlankStatusPanelWindow* self);
static void plank_status_panel_window_build_bluetooth (PlankStatusPanelWindow* self);
static void plank_status_panel_window_build_wifi (PlankStatusPanelWindow* self);
static void plank_status_panel_window_build_battery (PlankStatusPanelWindow* self);
static void plank_status_panel_window_build_clock (PlankStatusPanelWindow* self);
static gboolean plank_status_panel_window_run (const gchar* command,
                                        gchar** output);
static GtkWidget* plank_status_panel_window_section_label (PlankStatusPanelWindow* self,
                                                    const gchar* text);
static GtkWidget* plank_status_panel_window_device_selector (PlankStatusPanelWindow* self,
                                                      gboolean source);
static GtkWidget* plank_status_panel_window_modern_volume_bar (PlankStatusPanelWindow* self,
                                                        const gchar* target,
                                                        gdouble percent,
                                                        gdouble maximum,
                                                        const gchar* icon_name,
                                                        gboolean muted);
static gdouble plank_status_panel_window_get_wpctl_volume (PlankStatusPanelWindow* self,
                                                    const gchar* target);
static gboolean plank_status_panel_window_wpctl_muted (PlankStatusPanelWindow* self,
                                                const gchar* target);
static void __lambda70_ (PlankStatusPanelWindow* self);
static void plank_status_panel_window_launch (const gchar* command);
static void ___lambda70__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static Block28Data* block28_data_ref (Block28Data* _data28_);
static void block28_data_unref (void * _userdata_);
static GtkToggleButton* plank_status_panel_window_icon_toggle_button (PlankStatusPanelWindow* self,
                                                               const gchar* icon,
                                                               gboolean active);
static void __lambda68_ (Block28Data* _data28_);
static void plank_status_panel_window_run_action (const gchar* command);
static void ___lambda68__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self);
static void __lambda69_ (Block28Data* _data28_);
static void ___lambda69__gtk_range_value_changed (GtkRange* _sender,
                                           gpointer self);
static Block29Data* block29_data_ref (Block29Data* _data29_);
static void block29_data_unref (void * _userdata_);
static gchar* plank_status_panel_window_friendly_device_name (PlankStatusPanelWindow* self,
                                                       const gchar* name);
static void __lambda65_ (Block29Data* _data29_);
static gboolean ___lambda66_ (PlankStatusPanelWindow* self);
static gboolean ____lambda66__gsource_func (gpointer self);
static void ___lambda65__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void __lambda67_ (Block29Data* _data29_);
static void plank_status_panel_window_move_active_streams (PlankStatusPanelWindow* self,
                                                    gboolean source,
                                                    const gchar* device);
static void ___lambda67__gtk_combo_box_changed (GtkComboBox* _sender,
                                         gpointer self);
static gboolean plank_status_panel_window_contains (const gchar* command,
                                             const gchar* needle);
static GtkWidget* plank_status_panel_window_switch_row (PlankStatusPanelWindow* self,
                                                 const gchar* label,
                                                 gboolean state,
                                                 PlankStatusPanelWindowSwitchChanged changed,
                                                 gpointer changed_target,
                                                 GDestroyNotify changed_target_destroy_notify);
static void __lambda72_ (PlankStatusPanelWindow* self,
                  gboolean state);
static void ___lambda72__plank_status_panel_window_switch_changed (gboolean state,
                                                            gpointer self);
static GtkWidget* plank_status_panel_window_info_row (PlankStatusPanelWindow* self,
                                               const gchar* title,
                                               const gchar* subtitle);
static void __lambda73_ (PlankStatusPanelWindow* self,
                  gboolean state);
static void ___lambda73__plank_status_panel_window_switch_changed (gboolean state,
                                                            gpointer self);
static Block30Data* block30_data_ref (Block30Data* _data30_);
static void block30_data_unref (void * _userdata_);
static void __lambda71_ (Block30Data* _data30_);
static void ___lambda71__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void plank_status_panel_window_finalize (GObject * obj);
static GType plank_status_panel_window_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static inline gpointer
plank_status_panel_window_get_instance_private (PlankStatusPanelWindow* self)
{
	return G_STRUCT_MEMBER_P (self, PlankStatusPanelWindow_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static Block27Data*
block27_data_ref (Block27Data* _data27_)
{
	g_atomic_int_inc (&_data27_->_ref_count_);
	return _data27_;
}

static void
block27_data_unref (void * _userdata_)
{
	Block27Data* _data27_;
	_data27_ = (Block27Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data27_->_ref_count_)) {
		PlankStatusPanelWindow* self;
		self = _data27_->self;
		_g_object_unref0 (_data27_->controller);
		_g_object_unref0 (self);
		g_slice_free (Block27Data, _data27_);
	}
}

static gboolean
__lambda29_ (PlankStatusPanelWindow* self)
{
	gboolean result;
	if (!self->priv->device_popup_open) {
		plank_status_panel_window_dismiss (self);
	}
	result = FALSE;
	return result;
}

static gboolean
___lambda29__gtk_widget_focus_out_event (GtkWidget* _sender,
                                         GdkEventFocus* event,
                                         gpointer self)
{
	gboolean result;
	result = __lambda29_ ((PlankStatusPanelWindow*) self);
	return result;
}

static void
__lambda30_ (Block27Data* _data27_)
{
	PlankStatusPanelWindow* self;
	PlankHideManager* _tmp0_;
	PlankHideManager* _tmp1_;
	PlankHideManager* _tmp2_;
	PlankHideManager* _tmp3_;
	self = _data27_->self;
	_tmp0_ = plank_dock_controller_get_hide_manager (_data27_->controller);
	_tmp1_ = _tmp0_;
	plank_hide_manager_set_ExternalMenuVisible (_tmp1_, TRUE);
	_tmp2_ = plank_dock_controller_get_hide_manager (_data27_->controller);
	_tmp3_ = _tmp2_;
	plank_hide_manager_update_hovered (_tmp3_);
}

static void
___lambda30__gtk_widget_show (GtkWidget* _sender,
                              gpointer self)
{
	__lambda30_ (self);
}

static void
__lambda64_ (Block27Data* _data27_)
{
	PlankStatusPanelWindow* self;
	PlankHideManager* _tmp0_;
	PlankHideManager* _tmp1_;
	PlankHideManager* _tmp2_;
	PlankHideManager* _tmp3_;
	self = _data27_->self;
	_tmp0_ = plank_dock_controller_get_hide_manager (_data27_->controller);
	_tmp1_ = _tmp0_;
	plank_hide_manager_set_ExternalMenuVisible (_tmp1_, FALSE);
	_tmp2_ = plank_dock_controller_get_hide_manager (_data27_->controller);
	_tmp3_ = _tmp2_;
	plank_hide_manager_update_hovered (_tmp3_);
}

static void
___lambda64__gtk_widget_hide (GtkWidget* _sender,
                              gpointer self)
{
	__lambda64_ (self);
}

PlankStatusPanelWindow*
plank_status_panel_window_construct (GType object_type,
                                     PlankDockController* controller)
{
	PlankStatusPanelWindow * self = NULL;
	Block27Data* _data27_;
	PlankDockController* _tmp0_;
	GdkGeometry geometry = {0};
	GdkGeometry _tmp1_ = {0};
	GdkGeometry _tmp2_;
	GdkVisual* visual = NULL;
	GdkScreen* _tmp3_;
	GdkVisual* _tmp4_;
	GdkVisual* _tmp5_;
	GdkVisual* _tmp6_;
	GtkStyleContext* _tmp8_;
	GtkBox* card = NULL;
	GtkBox* _tmp9_;
	GtkStyleContext* _tmp10_;
	GtkBox* _tmp11_;
	GtkScrolledWindow* scroll = NULL;
	GtkScrolledWindow* _tmp12_;
	GtkStyleContext* _tmp13_;
	GtkBox* _tmp14_;
	GtkBox* _tmp15_;
	GtkBox* _tmp16_;
	GtkStyleContext* _tmp17_;
	GtkBox* _tmp18_;
	g_return_val_if_fail (controller != NULL, NULL);
	_data27_ = g_slice_new0 (Block27Data);
	_data27_->_ref_count_ = 1;
	_tmp0_ = _g_object_ref0 (controller);
	_g_object_unref0 (_data27_->controller);
	_data27_->controller = _tmp0_;
	self = (PlankStatusPanelWindow*) g_object_new (object_type, "type", GTK_WINDOW_TOPLEVEL, NULL);
	_data27_->self = g_object_ref (self);
	self->priv->controller = _data27_->controller;
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_skip_pager_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_keep_above ((GtkWindow*) self, TRUE);
	gtk_window_set_type_hint ((GtkWindow*) self, GDK_WINDOW_TYPE_HINT_DIALOG);
	gtk_window_set_default_size ((GtkWindow*) self, PLANK_STATUS_PANEL_WINDOW_PANEL_WIDTH, PLANK_STATUS_PANEL_WINDOW_PANEL_HEIGHT);
	geometry = _tmp1_;
	geometry.min_width = PLANK_STATUS_PANEL_WINDOW_PANEL_WIDTH;
	geometry.max_width = PLANK_STATUS_PANEL_WINDOW_PANEL_WIDTH;
	geometry.min_height = PLANK_STATUS_PANEL_WINDOW_PANEL_HEIGHT;
	geometry.max_height = PLANK_STATUS_PANEL_WINDOW_PANEL_HEIGHT;
	_tmp2_ = geometry;
	gtk_window_set_geometry_hints ((GtkWindow*) self, NULL, &_tmp2_, GDK_HINT_MIN_SIZE | GDK_HINT_MAX_SIZE);
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
	_tmp3_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp4_ = gdk_screen_get_rgba_visual (_tmp3_);
	_tmp5_ = _g_object_ref0 (_tmp4_);
	visual = _tmp5_;
	_tmp6_ = visual;
	if (_tmp6_ != NULL) {
		GdkVisual* _tmp7_;
		_tmp7_ = visual;
		gtk_widget_set_visual ((GtkWidget*) self, _tmp7_);
	}
	_tmp8_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_class (_tmp8_, "plank-status-panel");
	_tmp9_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp9_);
	card = _tmp9_;
	g_object_set ((GtkWidget*) card, "margin", 10, NULL);
	_tmp10_ = gtk_widget_get_style_context ((GtkWidget*) card);
	gtk_style_context_add_class (_tmp10_, "status-card");
	_tmp11_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 3);
	g_object_ref_sink (_tmp11_);
	_g_object_unref0 (self->priv->content);
	self->priv->content = _tmp11_;
	_tmp12_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp12_);
	scroll = _tmp12_;
	g_object_set (scroll, "hscrollbar-policy", GTK_POLICY_NEVER, NULL);
	g_object_set (scroll, "vscrollbar-policy", GTK_POLICY_NEVER, NULL);
	gtk_scrolled_window_set_overlay_scrolling (scroll, TRUE);
	gtk_scrolled_window_set_propagate_natural_width (scroll, FALSE);
	gtk_scrolled_window_set_propagate_natural_height (scroll, FALSE);
	_tmp13_ = gtk_widget_get_style_context ((GtkWidget*) scroll);
	gtk_style_context_add_class (_tmp13_, "status-scroll");
	_tmp14_ = self->priv->content;
	gtk_container_add ((GtkContainer*) scroll, (GtkWidget*) _tmp14_);
	gtk_box_pack_start (card, (GtkWidget*) scroll, TRUE, TRUE, (guint) 0);
	_tmp15_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp15_);
	_g_object_unref0 (self->priv->footer);
	self->priv->footer = _tmp15_;
	_tmp16_ = self->priv->footer;
	_tmp17_ = gtk_widget_get_style_context ((GtkWidget*) _tmp16_);
	gtk_style_context_add_class (_tmp17_, "status-footer");
	_tmp18_ = self->priv->footer;
	gtk_box_pack_end (card, (GtkWidget*) _tmp18_, FALSE, FALSE, (guint) 0);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) card);
	g_signal_connect_object ((GtkWidget*) self, "focus-out-event", (GCallback) ___lambda29__gtk_widget_focus_out_event, self, 0);
	g_signal_connect_data ((GtkWidget*) self, "show", (GCallback) ___lambda30__gtk_widget_show, block27_data_ref (_data27_), (GClosureNotify) block27_data_unref, 0);
	g_signal_connect_data ((GtkWidget*) self, "hide", (GCallback) ___lambda64__gtk_widget_hide, block27_data_ref (_data27_), (GClosureNotify) block27_data_unref, 0);
	_g_object_unref0 (scroll);
	_g_object_unref0 (card);
	_g_object_unref0 (visual);
	block27_data_unref (_data27_);
	_data27_ = NULL;
	return self;
}

PlankStatusPanelWindow*
plank_status_panel_window_new (PlankDockController* controller)
{
	return plank_status_panel_window_construct (PLANK_TYPE_STATUS_PANEL_WINDOW, controller);
}

static gboolean
__lambda75_ (PlankStatusPanelWindow* self)
{
	gboolean result;
	plank_status_panel_window_position_over_item (self);
	result = FALSE;
	return result;
}

static gboolean
___lambda75__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda75_ ((PlankStatusPanelWindow*) self);
	return result;
}

static gboolean
__lambda74_ (PlankStatusPanelWindow* self)
{
	gboolean result;
	gtk_window_resize ((GtkWindow*) self, self->priv->active_panel_width, self->priv->active_panel_height);
	plank_status_panel_window_position_over_item (self);
	gtk_widget_set_opacity ((GtkWidget*) self, 1.0);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda75__gsource_func, g_object_ref (self), g_object_unref);
	result = FALSE;
	return result;
}

static gboolean
___lambda74__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda74_ ((PlankStatusPanelWindow*) self);
	return result;
}

void
plank_status_panel_window_toggle (PlankStatusPanelWindow* self,
                                  PlankStatusIndicatorItem* item)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_;
	gboolean _tmp2_;
	PlankStatusIndicatorItem* _tmp4_;
	PlankStatusIndicatorKind _tmp5_;
	PlankStatusIndicatorKind _tmp6_;
	PlankStatusIndicatorKind _tmp7_;
	PlankStatusIndicatorKind _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	_tmp1_ = gtk_widget_get_visible ((GtkWidget*) self);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		PlankStatusIndicatorItem* _tmp3_;
		_tmp3_ = self->priv->current_item;
		_tmp0_ = _tmp3_ == item;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		plank_status_panel_window_dismiss (self);
		return;
	}
	_tmp4_ = _g_object_ref0 (item);
	_g_object_unref0 (self->priv->current_item);
	self->priv->current_item = _tmp4_;
	_tmp5_ = plank_status_indicator_item_get_Kind (item);
	_tmp6_ = _tmp5_;
	plank_status_panel_window_apply_geometry (self, _tmp6_);
	_tmp7_ = plank_status_indicator_item_get_Kind (item);
	_tmp8_ = _tmp7_;
	plank_status_panel_window_rebuild (self, _tmp8_);
	plank_status_panel_window_apply_theme (self);
	gtk_widget_set_opacity ((GtkWidget*) self, 0.0);
	gtk_widget_show_all ((GtkWidget*) self);
	gtk_window_present ((GtkWindow*) self);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda74__gsource_func, g_object_ref (self), g_object_unref);
}

static void
plank_status_panel_window_apply_geometry (PlankStatusPanelWindow* self,
                                          PlankStatusIndicatorKind kind)
{
	GdkGeometry geometry = {0};
	GdkGeometry _tmp8_ = {0};
	GdkGeometry _tmp9_;
	g_return_if_fail (self != NULL);
	if (kind == PLANK_STATUS_INDICATOR_KIND_VOLUME) {
		GdkRectangle workarea = {0};
		GdkRectangle _tmp0_ = {0};
		GdkRectangle bar = {0};
		PlankDockController* _tmp1_;
		PlankPositionManager* _tmp2_;
		PlankPositionManager* _tmp3_;
		GdkRectangle _tmp4_ = {0};
		gint available_above = 0;
		GdkRectangle _tmp5_;
		GdkRectangle _tmp6_;
		gint square_size = 0;
		GdkRectangle _tmp7_;
		plank_status_panel_window_active_workarea (self, &_tmp0_);
		workarea = _tmp0_;
		_tmp1_ = self->priv->controller;
		_tmp2_ = plank_dock_controller_get_position_manager (_tmp1_);
		_tmp3_ = _tmp2_;
		plank_position_manager_get_screen_background_region (_tmp3_, &_tmp4_);
		bar = _tmp4_;
		_tmp5_ = bar;
		_tmp6_ = workarea;
		available_above = (_tmp5_.y - PLANK_STATUS_PANEL_WINDOW_PANEL_GAP) - _tmp6_.y;
		_tmp7_ = workarea;
		square_size = MIN (PLANK_STATUS_PANEL_WINDOW_VOLUME_PANEL_SIZE, MIN (_tmp7_.width - 20, available_above));
		self->priv->active_panel_height = MAX (160, square_size);
		self->priv->active_panel_width = self->priv->active_panel_height;
	} else {
		self->priv->active_panel_width = PLANK_STATUS_PANEL_WINDOW_PANEL_WIDTH;
		self->priv->active_panel_height = PLANK_STATUS_PANEL_WINDOW_PANEL_HEIGHT;
	}
	geometry = _tmp8_;
	geometry.min_width = self->priv->active_panel_width;
	geometry.max_width = self->priv->active_panel_width;
	geometry.min_height = self->priv->active_panel_height;
	geometry.max_height = self->priv->active_panel_height;
	_tmp9_ = geometry;
	gtk_window_set_geometry_hints ((GtkWindow*) self, NULL, &_tmp9_, GDK_HINT_MIN_SIZE | GDK_HINT_MAX_SIZE);
	gtk_widget_set_size_request ((GtkWidget*) self, self->priv->active_panel_width, self->priv->active_panel_height);
	gtk_window_set_default_size ((GtkWindow*) self, self->priv->active_panel_width, self->priv->active_panel_height);
	gtk_window_resize ((GtkWindow*) self, self->priv->active_panel_width, self->priv->active_panel_height);
}

void
plank_status_panel_window_dismiss (PlankStatusPanelWindow* self)
{
	gboolean _tmp0_;
	gboolean _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_visible ((GtkWidget*) self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		gtk_widget_hide ((GtkWidget*) self);
	}
}

static void
plank_status_panel_window_rebuild (PlankStatusPanelWindow* self,
                                   PlankStatusIndicatorKind kind)
{
	GtkBox* _tmp0_;
	GList* _tmp1_;
	GtkBox* _tmp4_;
	GList* _tmp5_;
	GtkBox* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GtkWidget* _tmp13_;
	GtkWidget* _tmp14_;
	GtkBox* _tmp15_;
	GtkSeparator* _tmp16_;
	GtkSeparator* _tmp17_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->content;
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
		child_collection = _tmp1_;
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
			GtkWidget* child = NULL;
			child = (GtkWidget*) child_it->data;
			{
				GtkBox* _tmp2_;
				GtkWidget* _tmp3_;
				_tmp2_ = self->priv->content;
				_tmp3_ = child;
				gtk_container_remove ((GtkContainer*) _tmp2_, _tmp3_);
			}
		}
		(child_collection == NULL) ? NULL : (child_collection = (g_list_free (child_collection), NULL));
	}
	_tmp4_ = self->priv->footer;
	_tmp5_ = gtk_container_get_children ((GtkContainer*) _tmp4_);
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
		child_collection = _tmp5_;
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
			GtkWidget* child = NULL;
			child = (GtkWidget*) child_it->data;
			{
				GtkBox* _tmp6_;
				GtkWidget* _tmp7_;
				_tmp6_ = self->priv->footer;
				_tmp7_ = child;
				gtk_container_remove ((GtkContainer*) _tmp6_, _tmp7_);
			}
		}
		(child_collection == NULL) ? NULL : (child_collection = (g_list_free (child_collection), NULL));
	}
	_tmp8_ = self->priv->content;
	_tmp9_ = plank_status_panel_window_label_for_kind (kind);
	_tmp10_ = _tmp9_;
	_tmp11_ = plank_status_panel_window_icon_for_kind (kind);
	_tmp12_ = _tmp11_;
	_tmp13_ = plank_status_panel_window_title_row (self, _tmp10_, _tmp12_);
	_tmp14_ = _tmp13_;
	gtk_box_pack_start (_tmp8_, _tmp14_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp14_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp10_);
	_tmp15_ = self->priv->content;
	_tmp16_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
	g_object_ref_sink (_tmp16_);
	_tmp17_ = _tmp16_;
	gtk_box_pack_start (_tmp15_, (GtkWidget*) _tmp17_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp17_);
	switch (kind) {
		case PLANK_STATUS_INDICATOR_KIND_VOLUME:
		{
			plank_status_panel_window_build_volume (self);
			break;
		}
		case PLANK_STATUS_INDICATOR_KIND_BLUETOOTH:
		{
			plank_status_panel_window_build_bluetooth (self);
			break;
		}
		case PLANK_STATUS_INDICATOR_KIND_WIFI:
		{
			plank_status_panel_window_build_wifi (self);
			break;
		}
		case PLANK_STATUS_INDICATOR_KIND_BATTERY:
		{
			plank_status_panel_window_build_battery (self);
			break;
		}
		case PLANK_STATUS_INDICATOR_KIND_CLOCK:
		{
			plank_status_panel_window_build_clock (self);
			break;
		}
		default:
		{
			break;
		}
	}
}

static GtkWidget*
plank_status_panel_window_title_row (PlankStatusPanelWindow* self,
                                     const gchar* title,
                                     const gchar* icon)
{
	GtkBox* box = NULL;
	GtkBox* _tmp0_;
	GtkStyleContext* _tmp1_;
	GtkImage* _tmp2_;
	GtkImage* _tmp3_;
	GtkLabel* label = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_;
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (title != NULL, NULL);
	g_return_val_if_fail (icon != NULL, NULL);
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 10);
	g_object_ref_sink (_tmp0_);
	box = _tmp0_;
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) box);
	gtk_style_context_add_class (_tmp1_, "status-title");
	_tmp2_ = (GtkImage*) gtk_image_new_from_icon_name (icon, (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	gtk_box_pack_start (box, (GtkWidget*) _tmp3_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp3_);
	_tmp4_ = (GtkLabel*) gtk_label_new (title);
	gtk_label_set_xalign (_tmp4_, 0.0f);
	g_object_ref_sink (_tmp4_);
	label = _tmp4_;
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) label);
	gtk_style_context_add_class (_tmp5_, "status-title-label");
	gtk_box_pack_start (box, (GtkWidget*) label, TRUE, TRUE, (guint) 0);
	result = (GtkWidget*) box;
	_g_object_unref0 (label);
	return result;
}

static gdouble
double_parse (const gchar* str)
{
	gdouble result;
	g_return_val_if_fail (str != NULL, 0.0);
	result = g_ascii_strtod (str, NULL);
	return result;
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
	result = _tmp0_ != NULL;
	return result;
}

static void
__lambda70_ (PlankStatusPanelWindow* self)
{
	plank_status_panel_window_launch ("pavucontrol");
}

static void
___lambda70__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
	__lambda70_ ((PlankStatusPanelWindow*) self);
}

static void
plank_status_panel_window_build_volume (PlankStatusPanelWindow* self)
{
	gchar* output = NULL;
	gdouble percent = 0.0;
	gboolean muted = FALSE;
	gchar* _tmp0_ = NULL;
	gboolean _tmp1_;
	GtkBox* _tmp9_;
	GtkWidget* _tmp10_;
	GtkWidget* _tmp11_;
	GtkBox* _tmp12_;
	GtkWidget* _tmp13_;
	GtkWidget* _tmp14_;
	GtkBox* _tmp15_;
	GtkWidget* _tmp16_;
	GtkWidget* _tmp17_;
	GtkBox* _tmp18_;
	GtkWidget* _tmp19_;
	GtkWidget* _tmp20_;
	GtkBox* _tmp21_;
	GtkWidget* _tmp22_;
	GtkWidget* _tmp23_;
	gdouble mic_percent = 0.0;
	GtkBox* _tmp24_;
	GtkWidget* _tmp25_;
	GtkWidget* _tmp26_;
	GtkButton* settings = NULL;
	GtkButton* _tmp27_;
	GtkStyleContext* _tmp28_;
	GtkBox* _tmp29_;
	g_return_if_fail (self != NULL);
	percent = 0.0;
	muted = FALSE;
	_tmp1_ = plank_status_panel_window_run ("wpctl get-volume @DEFAULT_AUDIO_SINK@", &_tmp0_);
	_g_free0 (output);
	output = _tmp0_;
	if (_tmp1_) {
		gchar** fields = NULL;
		const gchar* _tmp2_;
		gchar** _tmp3_;
		gchar** _tmp4_;
		gint fields_length1;
		gint _fields_size_;
		gchar** _tmp5_;
		gint _tmp5__length1;
		const gchar* _tmp8_;
		_tmp2_ = output;
		_tmp4_ = _tmp3_ = g_strsplit (_tmp2_, " ", 0);
		fields = _tmp4_;
		fields_length1 = _vala_array_length (_tmp3_);
		_fields_size_ = fields_length1;
		_tmp5_ = fields;
		_tmp5__length1 = fields_length1;
		if (_tmp5__length1 > 1) {
			gchar** _tmp6_;
			gint _tmp6__length1;
			const gchar* _tmp7_;
			_tmp6_ = fields;
			_tmp6__length1 = fields_length1;
			_tmp7_ = _tmp6_[1];
			percent = double_parse (_tmp7_) * 100.0;
		}
		_tmp8_ = output;
		muted = string_contains (_tmp8_, "[MUTED]");
		fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
	}
	_tmp9_ = self->priv->content;
	_tmp10_ = plank_status_panel_window_section_label (self, _ ("Output"));
	_tmp11_ = _tmp10_;
	gtk_box_pack_start (_tmp9_, _tmp11_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp11_);
	_tmp12_ = self->priv->content;
	_tmp13_ = plank_status_panel_window_device_selector (self, FALSE);
	_tmp14_ = _tmp13_;
	gtk_box_pack_start (_tmp12_, _tmp14_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp14_);
	_tmp15_ = self->priv->content;
	_tmp16_ = plank_status_panel_window_modern_volume_bar (self, "@DEFAULT_AUDIO_SINK@", percent, (gdouble) 150, "audio-volume-high-symbolic", muted);
	_tmp17_ = _tmp16_;
	gtk_box_pack_start (_tmp15_, _tmp17_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp17_);
	_tmp18_ = self->priv->content;
	_tmp19_ = plank_status_panel_window_section_label (self, _ ("Microphone"));
	_tmp20_ = _tmp19_;
	gtk_box_pack_start (_tmp18_, _tmp20_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp20_);
	_tmp21_ = self->priv->content;
	_tmp22_ = plank_status_panel_window_device_selector (self, TRUE);
	_tmp23_ = _tmp22_;
	gtk_box_pack_start (_tmp21_, _tmp23_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp23_);
	mic_percent = plank_status_panel_window_get_wpctl_volume (self, "@DEFAULT_AUDIO_SOURCE@");
	_tmp24_ = self->priv->content;
	_tmp25_ = plank_status_panel_window_modern_volume_bar (self, "@DEFAULT_AUDIO_SOURCE@", mic_percent, (gdouble) 100, "audio-input-microphone-symbolic", plank_status_panel_window_wpctl_muted (self, "@DEFAULT_AUDIO_SOURCE@"));
	_tmp26_ = _tmp25_;
	gtk_box_pack_start (_tmp24_, _tmp26_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp26_);
	_tmp27_ = (GtkButton*) gtk_button_new_with_label (_ ("Advanced sound settings"));
	g_object_ref_sink (_tmp27_);
	settings = _tmp27_;
	_tmp28_ = gtk_widget_get_style_context ((GtkWidget*) settings);
	gtk_style_context_add_class (_tmp28_, "status-action-button");
	g_signal_connect_object (settings, "clicked", (GCallback) ___lambda70__gtk_button_clicked, self, 0);
	_tmp29_ = self->priv->footer;
	gtk_box_pack_start (_tmp29_, (GtkWidget*) settings, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (settings);
	_g_free0 (output);
}

static Block28Data*
block28_data_ref (Block28Data* _data28_)
{
	g_atomic_int_inc (&_data28_->_ref_count_);
	return _data28_;
}

static void
block28_data_unref (void * _userdata_)
{
	Block28Data* _data28_;
	_data28_ = (Block28Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data28_->_ref_count_)) {
		PlankStatusPanelWindow* self;
		self = _data28_->self;
		_g_object_unref0 (_data28_->value);
		_g_object_unref0 (_data28_->icon);
		_g_object_unref0 (_data28_->scale);
		_g_free0 (_data28_->target);
		_g_object_unref0 (self);
		g_slice_free (Block28Data, _data28_);
	}
}

static void
__lambda68_ (Block28Data* _data28_)
{
	PlankStatusPanelWindow* self;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_;
	gboolean _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	self = _data28_->self;
	_tmp1_ = gtk_toggle_button_get_active (_data28_->icon);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		_tmp0_ = "1";
	} else {
		_tmp0_ = "0";
	}
	_tmp3_ = g_strdup_printf ("wpctl set-mute %s %s", _data28_->target, _tmp0_);
	_tmp4_ = _tmp3_;
	plank_status_panel_window_run_action (_tmp4_);
	_g_free0 (_tmp4_);
}

static void
___lambda68__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                        gpointer self)
{
	__lambda68_ (self);
}

static void
__lambda69_ (Block28Data* _data28_)
{
	PlankStatusPanelWindow* self;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	self = _data28_->self;
	_tmp0_ = g_strdup_printf ("wpctl set-volume %s %.0f%%", _data28_->target, gtk_range_get_value ((GtkRange*) _data28_->scale));
	_tmp1_ = _tmp0_;
	plank_status_panel_window_run_action (_tmp1_);
	_g_free0 (_tmp1_);
	_tmp2_ = g_strdup_printf ("%.0f%%", gtk_range_get_value ((GtkRange*) _data28_->scale));
	_tmp3_ = _tmp2_;
	gtk_label_set_label (_data28_->value, _tmp3_);
	_g_free0 (_tmp3_);
}

static void
___lambda69__gtk_range_value_changed (GtkRange* _sender,
                                      gpointer self)
{
	__lambda69_ (self);
}

static GtkWidget*
plank_status_panel_window_modern_volume_bar (PlankStatusPanelWindow* self,
                                             const gchar* target,
                                             gdouble percent,
                                             gdouble maximum,
                                             const gchar* icon_name,
                                             gboolean muted)
{
	Block28Data* _data28_;
	gchar* _tmp0_;
	GtkOverlay* overlay = NULL;
	GtkOverlay* _tmp1_;
	GtkStyleContext* _tmp2_;
	GtkScale* _tmp3_;
	GtkStyleContext* _tmp4_;
	GtkToggleButton* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	GtkLabel* _tmp8_;
	GtkLabel* _tmp9_;
	GtkStyleContext* _tmp10_;
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (target != NULL, NULL);
	g_return_val_if_fail (icon_name != NULL, NULL);
	_data28_ = g_slice_new0 (Block28Data);
	_data28_->_ref_count_ = 1;
	_data28_->self = g_object_ref (self);
	_tmp0_ = g_strdup (target);
	_g_free0 (_data28_->target);
	_data28_->target = _tmp0_;
	_tmp1_ = (GtkOverlay*) gtk_overlay_new ();
	g_object_ref_sink (_tmp1_);
	overlay = _tmp1_;
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) overlay);
	gtk_style_context_add_class (_tmp2_, "modern-volume-bar");
	_tmp3_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_HORIZONTAL, (gdouble) 0, maximum, (gdouble) 1);
	g_object_ref_sink (_tmp3_);
	_data28_->scale = _tmp3_;
	gtk_scale_set_draw_value (_data28_->scale, FALSE);
	gtk_scale_set_has_origin (_data28_->scale, TRUE);
	g_object_set ((GtkWidget*) _data28_->scale, "height-request", 36, NULL);
	gtk_range_set_value ((GtkRange*) _data28_->scale, percent);
	_tmp4_ = gtk_widget_get_style_context ((GtkWidget*) _data28_->scale);
	gtk_style_context_add_class (_tmp4_, "modern-volume-scale");
	gtk_container_add ((GtkContainer*) overlay, (GtkWidget*) _data28_->scale);
	_tmp5_ = plank_status_panel_window_icon_toggle_button (self, icon_name, muted);
	_data28_->icon = _tmp5_;
	gtk_widget_set_halign ((GtkWidget*) _data28_->icon, GTK_ALIGN_START);
	gtk_widget_set_valign ((GtkWidget*) _data28_->icon, GTK_ALIGN_CENTER);
	gtk_widget_set_margin_start ((GtkWidget*) _data28_->icon, 5);
	g_signal_connect_data (_data28_->icon, "toggled", (GCallback) ___lambda68__gtk_toggle_button_toggled, block28_data_ref (_data28_), (GClosureNotify) block28_data_unref, 0);
	gtk_overlay_add_overlay (overlay, (GtkWidget*) _data28_->icon);
	_tmp6_ = g_strdup_printf ("%.0f%%", percent);
	_tmp7_ = _tmp6_;
	_tmp8_ = (GtkLabel*) gtk_label_new (_tmp7_);
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	_data28_->value = _tmp9_;
	gtk_widget_set_halign ((GtkWidget*) _data28_->value, GTK_ALIGN_END);
	gtk_widget_set_valign ((GtkWidget*) _data28_->value, GTK_ALIGN_CENTER);
	gtk_widget_set_margin_end ((GtkWidget*) _data28_->value, 10);
	_tmp10_ = gtk_widget_get_style_context ((GtkWidget*) _data28_->value);
	gtk_style_context_add_class (_tmp10_, "modern-volume-value");
	gtk_overlay_add_overlay (overlay, (GtkWidget*) _data28_->value);
	gtk_overlay_set_overlay_pass_through (overlay, (GtkWidget*) _data28_->value, TRUE);
	g_signal_connect_data ((GtkRange*) _data28_->scale, "value-changed", (GCallback) ___lambda69__gtk_range_value_changed, block28_data_ref (_data28_), (GClosureNotify) block28_data_unref, 0);
	result = (GtkWidget*) overlay;
	block28_data_unref (_data28_);
	_data28_ = NULL;
	return result;
}

static GtkToggleButton*
plank_status_panel_window_icon_toggle_button (PlankStatusPanelWindow* self,
                                              const gchar* icon,
                                              gboolean active)
{
	GtkToggleButton* button = NULL;
	GtkToggleButton* _tmp0_;
	GtkStyleContext* _tmp1_;
	GtkImage* _tmp2_;
	GtkImage* _tmp3_;
	GtkToggleButton* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (icon != NULL, NULL);
	_tmp0_ = (GtkToggleButton*) gtk_toggle_button_new ();
	g_object_ref_sink (_tmp0_);
	button = _tmp0_;
	gtk_toggle_button_set_active (button, active);
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) button);
	gtk_style_context_add_class (_tmp1_, "status-icon-toggle");
	_tmp2_ = (GtkImage*) gtk_image_new_from_icon_name (icon, (GtkIconSize) GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	gtk_container_add ((GtkContainer*) button, (GtkWidget*) _tmp3_);
	_g_object_unref0 (_tmp3_);
	result = button;
	return result;
}

static GtkWidget*
plank_status_panel_window_section_label (PlankStatusPanelWindow* self,
                                         const gchar* text)
{
	GtkLabel* label = NULL;
	GtkLabel* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_;
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	_tmp0_ = (GtkLabel*) gtk_label_new (text);
	gtk_label_set_xalign (_tmp0_, 0.0f);
	g_object_ref_sink (_tmp0_);
	label = _tmp0_;
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) label);
	gtk_style_context_add_class (_tmp1_, "status-section-label");
	result = (GtkWidget*) label;
	return result;
}

static Block29Data*
block29_data_ref (Block29Data* _data29_)
{
	g_atomic_int_inc (&_data29_->_ref_count_);
	return _data29_;
}

static void
block29_data_unref (void * _userdata_)
{
	Block29Data* _data29_;
	_data29_ = (Block29Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data29_->_ref_count_)) {
		PlankStatusPanelWindow* self;
		self = _data29_->self;
		_g_object_unref0 (_data29_->combo);
		_g_object_unref0 (self);
		g_slice_free (Block29Data, _data29_);
	}
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}

static gboolean
___lambda66_ (PlankStatusPanelWindow* self)
{
	gboolean result;
	gtk_window_present ((GtkWindow*) self);
	result = FALSE;
	return result;
}

static gboolean
____lambda66__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda66_ ((PlankStatusPanelWindow*) self);
	return result;
}

static void
__lambda65_ (Block29Data* _data29_)
{
	PlankStatusPanelWindow* self;
	GtkComboBoxText* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_ = FALSE;
	self = _data29_->self;
	_tmp0_ = _data29_->combo;
	g_object_get ((GtkComboBox*) _tmp0_, "popup-shown", &_tmp1_, NULL);
	_tmp2_ = _tmp1_;
	self->priv->device_popup_open = _tmp2_;
	if (!self->priv->device_popup_open) {
		gboolean _tmp4_;
		gboolean _tmp5_;
		_tmp4_ = gtk_widget_get_visible ((GtkWidget*) self);
		_tmp5_ = _tmp4_;
		_tmp3_ = _tmp5_;
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ____lambda66__gsource_func, g_object_ref (self), g_object_unref);
	}
}

static void
___lambda65__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
	__lambda65_ (self);
}

static void
__lambda67_ (Block29Data* _data29_)
{
	PlankStatusPanelWindow* self;
	GtkComboBoxText* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	self = _data29_->self;
	_tmp0_ = _data29_->combo;
	_tmp1_ = gtk_combo_box_get_active_id ((GtkComboBox*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		const gchar* _tmp3_ = NULL;
		GtkComboBoxText* _tmp4_;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		GtkComboBoxText* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		if (_data29_->source) {
			_tmp3_ = "pactl set-default-source ";
		} else {
			_tmp3_ = "pactl set-default-sink ";
		}
		_tmp4_ = _data29_->combo;
		_tmp5_ = gtk_combo_box_get_active_id ((GtkComboBox*) _tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_shell_quote (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_strconcat (_tmp3_, _tmp8_, NULL);
		_tmp10_ = _tmp9_;
		plank_status_panel_window_run_action (_tmp10_);
		_g_free0 (_tmp10_);
		_g_free0 (_tmp8_);
		_tmp11_ = _data29_->combo;
		_tmp12_ = gtk_combo_box_get_active_id ((GtkComboBox*) _tmp11_);
		_tmp13_ = _tmp12_;
		plank_status_panel_window_move_active_streams (self, _data29_->source, _tmp13_);
	}
}

static void
___lambda67__gtk_combo_box_changed (GtkComboBox* _sender,
                                    gpointer self)
{
	__lambda67_ (self);
}

static GtkWidget*
plank_status_panel_window_device_selector (PlankStatusPanelWindow* self,
                                           gboolean source)
{
	Block29Data* _data29_;
	GtkBox* row = NULL;
	GtkBox* _tmp0_;
	GtkBox* _tmp1_;
	GtkStyleContext* _tmp2_;
	GtkComboBoxText* _tmp3_;
	GtkComboBoxText* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkComboBoxText* _tmp6_;
	GList* _tmp7_;
	gchar* current = NULL;
	gchar* _tmp13_;
	gchar* output = NULL;
	gchar* _tmp14_;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gboolean _tmp19_;
	GtkComboBoxText* _tmp38_;
	const gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	GtkComboBoxText* _tmp42_;
	GtkComboBoxText* _tmp43_;
	GtkBox* _tmp44_;
	GtkComboBoxText* _tmp45_;
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	_data29_ = g_slice_new0 (Block29Data);
	_data29_->_ref_count_ = 1;
	_data29_->self = g_object_ref (self);
	_data29_->source = source;
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 10);
	g_object_ref_sink (_tmp0_);
	row = _tmp0_;
	_tmp1_ = row;
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) _tmp1_);
	gtk_style_context_add_class (_tmp2_, "status-row");
	_tmp3_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp3_);
	_data29_->combo = _tmp3_;
	_tmp4_ = _data29_->combo;
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
	gtk_style_context_add_class (_tmp5_, "modern-device-selector");
	_tmp6_ = _data29_->combo;
	_tmp7_ = gtk_cell_layout_get_cells ((GtkCellLayout*) _tmp6_);
	{
		GList* renderer_collection = NULL;
		GList* renderer_it = NULL;
		renderer_collection = _tmp7_;
		for (renderer_it = renderer_collection; renderer_it != NULL; renderer_it = renderer_it->next) {
			GtkCellRenderer* renderer = NULL;
			renderer = (GtkCellRenderer*) renderer_it->data;
			{
				GtkCellRendererText* text_renderer = NULL;
				GtkCellRenderer* _tmp8_;
				GtkCellRendererText* _tmp9_;
				GtkCellRendererText* _tmp10_;
				_tmp8_ = renderer;
				_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp8_, gtk_cell_renderer_text_get_type ()) ? ((GtkCellRendererText*) _tmp8_) : NULL);
				text_renderer = _tmp9_;
				_tmp10_ = text_renderer;
				if (_tmp10_ != NULL) {
					GtkCellRendererText* _tmp11_;
					GtkCellRendererText* _tmp12_;
					_tmp11_ = text_renderer;
					g_object_set (_tmp11_, "ellipsize", PANGO_ELLIPSIZE_END, NULL);
					_tmp12_ = text_renderer;
					g_object_set (_tmp12_, "width-chars", 14, NULL);
				}
				_g_object_unref0 (text_renderer);
			}
		}
		(renderer_collection == NULL) ? NULL : (renderer_collection = (g_list_free (renderer_collection), NULL));
	}
	_tmp13_ = g_strdup ("");
	current = _tmp13_;
	_tmp14_ = g_strdup ("");
	output = _tmp14_;
	if (_data29_->source) {
		_tmp15_ = "pactl get-default-source";
	} else {
		_tmp15_ = "pactl get-default-sink";
	}
	plank_status_panel_window_run (_tmp15_, &_tmp16_);
	_g_free0 (current);
	current = _tmp16_;
	if (_data29_->source) {
		_tmp17_ = "pactl list short sources";
	} else {
		_tmp17_ = "pactl list short sinks";
	}
	_tmp19_ = plank_status_panel_window_run (_tmp17_, &_tmp18_);
	_g_free0 (output);
	output = _tmp18_;
	if (_tmp19_) {
		const gchar* _tmp20_;
		gchar** _tmp21_;
		gchar** _tmp22_;
		_tmp20_ = output;
		_tmp22_ = _tmp21_ = g_strsplit (_tmp20_, "\n", 0);
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
			line_collection = _tmp22_;
			line_collection_length1 = _vala_array_length (_tmp21_);
			for (line_it = 0; line_it < line_collection_length1; line_it = line_it + 1) {
				const gchar* line = NULL;
				line = line_collection[line_it];
				{
					gchar** fields = NULL;
					const gchar* _tmp23_;
					gchar** _tmp24_;
					gchar** _tmp25_;
					gint fields_length1;
					gint _fields_size_;
					gboolean _tmp26_ = FALSE;
					gchar** _tmp27_;
					gint _tmp27__length1;
					GtkComboBoxText* _tmp31_;
					gchar** _tmp32_;
					gint _tmp32__length1;
					const gchar* _tmp33_;
					gchar** _tmp34_;
					gint _tmp34__length1;
					const gchar* _tmp35_;
					gchar* _tmp36_;
					gchar* _tmp37_;
					_tmp23_ = line;
					_tmp25_ = _tmp24_ = g_strsplit (_tmp23_, "\t", 0);
					fields = _tmp25_;
					fields_length1 = _vala_array_length (_tmp24_);
					_fields_size_ = fields_length1;
					_tmp27_ = fields;
					_tmp27__length1 = fields_length1;
					if (_tmp27__length1 < 2) {
						_tmp26_ = TRUE;
					} else {
						gboolean _tmp28_ = FALSE;
						if (_data29_->source) {
							gchar** _tmp29_;
							gint _tmp29__length1;
							const gchar* _tmp30_;
							_tmp29_ = fields;
							_tmp29__length1 = fields_length1;
							_tmp30_ = _tmp29_[1];
							_tmp28_ = g_str_has_suffix (_tmp30_, ".monitor");
						} else {
							_tmp28_ = FALSE;
						}
						_tmp26_ = _tmp28_;
					}
					if (_tmp26_) {
						fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
						continue;
					}
					_tmp31_ = _data29_->combo;
					_tmp32_ = fields;
					_tmp32__length1 = fields_length1;
					_tmp33_ = _tmp32_[1];
					_tmp34_ = fields;
					_tmp34__length1 = fields_length1;
					_tmp35_ = _tmp34_[1];
					_tmp36_ = plank_status_panel_window_friendly_device_name (self, _tmp35_);
					_tmp37_ = _tmp36_;
					gtk_combo_box_text_append (_tmp31_, _tmp33_, _tmp37_);
					_g_free0 (_tmp37_);
					fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
				}
			}
			line_collection = (_vala_array_free (line_collection, line_collection_length1, (GDestroyNotify) g_free), NULL);
		}
	}
	_tmp38_ = _data29_->combo;
	_tmp39_ = current;
	_tmp40_ = string_strip (_tmp39_);
	_tmp41_ = _tmp40_;
	gtk_combo_box_set_active_id ((GtkComboBox*) _tmp38_, _tmp41_);
	_g_free0 (_tmp41_);
	_tmp42_ = _data29_->combo;
	g_signal_connect_data ((GObject*) _tmp42_, "notify::popup-shown", (GCallback) ___lambda65__g_object_notify, block29_data_ref (_data29_), (GClosureNotify) block29_data_unref, 0);
	_tmp43_ = _data29_->combo;
	g_signal_connect_data ((GtkComboBox*) _tmp43_, "changed", (GCallback) ___lambda67__gtk_combo_box_changed, block29_data_ref (_data29_), (GClosureNotify) block29_data_unref, 0);
	_tmp44_ = row;
	_tmp45_ = _data29_->combo;
	gtk_box_pack_start (_tmp44_, (GtkWidget*) _tmp45_, TRUE, TRUE, (guint) 0);
	result = (GtkWidget*) row;
	_g_free0 (output);
	_g_free0 (current);
	block29_data_unref (_data29_);
	_data29_ = NULL;
	return result;
}

static void
plank_status_panel_window_move_active_streams (PlankStatusPanelWindow* self,
                                               gboolean source,
                                               const gchar* device)
{
	gchar* output = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* list_command = NULL;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_;
	const gchar* _tmp5_;
	gchar** _tmp6_;
	gchar** _tmp7_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (device != NULL);
	if (source) {
		_tmp0_ = "pactl list short source-outputs";
	} else {
		_tmp0_ = "pactl list short sink-inputs";
	}
	_tmp1_ = g_strdup (_tmp0_);
	list_command = _tmp1_;
	_tmp2_ = list_command;
	_tmp4_ = plank_status_panel_window_run (_tmp2_, &_tmp3_);
	_g_free0 (output);
	output = _tmp3_;
	if (!_tmp4_) {
		_g_free0 (list_command);
		_g_free0 (output);
		return;
	}
	_tmp5_ = output;
	_tmp7_ = _tmp6_ = g_strsplit (_tmp5_, "\n", 0);
	{
		gchar** line_collection = NULL;
		gint line_collection_length1 = 0;
		gint _line_collection_size_ = 0;
		gint line_it = 0;
		line_collection = _tmp7_;
		line_collection_length1 = _vala_array_length (_tmp6_);
		for (line_it = 0; line_it < line_collection_length1; line_it = line_it + 1) {
			const gchar* line = NULL;
			line = line_collection[line_it];
			{
				gchar** fields = NULL;
				const gchar* _tmp8_;
				gchar** _tmp9_;
				gchar** _tmp10_;
				gint fields_length1;
				gint _fields_size_;
				gboolean _tmp11_ = FALSE;
				gchar** _tmp12_;
				gint _tmp12__length1;
				const gchar* _tmp15_ = NULL;
				gchar** _tmp16_;
				gint _tmp16__length1;
				const gchar* _tmp17_;
				gchar* _tmp18_;
				gchar* _tmp19_;
				gchar* _tmp20_;
				gchar* _tmp21_;
				gchar* _tmp22_;
				gchar* _tmp23_;
				gchar* _tmp24_;
				gchar* _tmp25_;
				_tmp8_ = line;
				_tmp10_ = _tmp9_ = g_strsplit (_tmp8_, "\t", 0);
				fields = _tmp10_;
				fields_length1 = _vala_array_length (_tmp9_);
				_fields_size_ = fields_length1;
				_tmp12_ = fields;
				_tmp12__length1 = fields_length1;
				if (_tmp12__length1 < 1) {
					_tmp11_ = TRUE;
				} else {
					gchar** _tmp13_;
					gint _tmp13__length1;
					const gchar* _tmp14_;
					_tmp13_ = fields;
					_tmp13__length1 = fields_length1;
					_tmp14_ = _tmp13_[0];
					_tmp11_ = g_strcmp0 (_tmp14_, "") == 0;
				}
				if (_tmp11_) {
					fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
					continue;
				}
				if (source) {
					_tmp15_ = "pactl move-source-output ";
				} else {
					_tmp15_ = "pactl move-sink-input ";
				}
				_tmp16_ = fields;
				_tmp16__length1 = fields_length1;
				_tmp17_ = _tmp16_[0];
				_tmp18_ = g_strconcat (_tmp15_, _tmp17_, NULL);
				_tmp19_ = _tmp18_;
				_tmp20_ = g_strconcat (_tmp19_, " ", NULL);
				_tmp21_ = _tmp20_;
				_tmp22_ = g_shell_quote (device);
				_tmp23_ = _tmp22_;
				_tmp24_ = g_strconcat (_tmp21_, _tmp23_, NULL);
				_tmp25_ = _tmp24_;
				plank_status_panel_window_run_action (_tmp25_);
				_g_free0 (_tmp25_);
				_g_free0 (_tmp23_);
				_g_free0 (_tmp21_);
				_g_free0 (_tmp19_);
				fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
			}
		}
		line_collection = (_vala_array_free (line_collection, line_collection_length1, (GDestroyNotify) g_free), NULL);
	}
	_g_free0 (list_command);
	_g_free0 (output);
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		g_clear_error (&_inner_error0_);
		g_assert_not_reached ();
	}
	__finally0:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

static gchar*
plank_status_panel_window_friendly_device_name (PlankStatusPanelWindow* self,
                                                const gchar* name)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = string_replace (name, "alsa_output.", "");
	_tmp1_ = _tmp0_;
	_tmp2_ = string_replace (_tmp1_, "alsa_input.", "");
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	_result_ = _tmp3_;
	_tmp4_ = _result_;
	_tmp5_ = string_replace (_tmp4_, "bluez_output.", "Bluetooth · ");
	_tmp6_ = _tmp5_;
	_tmp7_ = string_replace (_tmp6_, "bluez_input.", "Bluetooth · ");
	_g_free0 (_result_);
	_result_ = _tmp7_;
	_g_free0 (_tmp6_);
	_tmp8_ = _result_;
	_tmp9_ = string_replace (_tmp8_, "_", " ");
	_tmp10_ = _tmp9_;
	_tmp11_ = string_replace (_tmp10_, ".", " · ");
	_g_free0 (_result_);
	_result_ = _tmp11_;
	_g_free0 (_tmp10_);
	result = _result_;
	return result;
}

static gdouble
plank_status_panel_window_get_wpctl_volume (PlankStatusPanelWindow* self,
                                            const gchar* target)
{
	gchar* output = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gboolean _tmp3_;
	gboolean _tmp4_;
	gchar** fields = NULL;
	const gchar* _tmp5_;
	gchar** _tmp6_;
	gchar** _tmp7_;
	gint fields_length1;
	gint _fields_size_;
	gdouble _tmp8_ = 0.0;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	g_return_val_if_fail (target != NULL, 0.0);
	_tmp0_ = g_strconcat ("wpctl get-volume ", target, NULL);
	_tmp1_ = _tmp0_;
	_tmp3_ = plank_status_panel_window_run (_tmp1_, &_tmp2_);
	_g_free0 (output);
	output = _tmp2_;
	_tmp4_ = !_tmp3_;
	_g_free0 (_tmp1_);
	if (_tmp4_) {
		result = 0.0;
		_g_free0 (output);
		return result;
	}
	_tmp5_ = output;
	_tmp7_ = _tmp6_ = g_strsplit (_tmp5_, " ", 0);
	fields = _tmp7_;
	fields_length1 = _vala_array_length (_tmp6_);
	_fields_size_ = fields_length1;
	_tmp9_ = fields;
	_tmp9__length1 = fields_length1;
	if (_tmp9__length1 > 1) {
		gchar** _tmp10_;
		gint _tmp10__length1;
		const gchar* _tmp11_;
		_tmp10_ = fields;
		_tmp10__length1 = fields_length1;
		_tmp11_ = _tmp10_[1];
		_tmp8_ = double_parse (_tmp11_) * 100.0;
	} else {
		_tmp8_ = 0.0;
	}
	result = _tmp8_;
	fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (output);
	return result;
}

static gboolean
plank_status_panel_window_wpctl_muted (PlankStatusPanelWindow* self,
                                       const gchar* target)
{
	gchar* output = NULL;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_;
	gboolean _tmp5_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (target != NULL, FALSE);
	_tmp1_ = g_strconcat ("wpctl get-volume ", target, NULL);
	_tmp2_ = _tmp1_;
	_tmp4_ = plank_status_panel_window_run (_tmp2_, &_tmp3_);
	_g_free0 (output);
	output = _tmp3_;
	_tmp5_ = _tmp4_;
	_g_free0 (_tmp2_);
	if (_tmp5_) {
		const gchar* _tmp6_;
		_tmp6_ = output;
		_tmp0_ = string_contains (_tmp6_, "[MUTED]");
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	_g_free0 (output);
	return result;
}

static void
__lambda72_ (PlankStatusPanelWindow* self,
             gboolean state)
{
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	if (state) {
		_tmp0_ = "on";
	} else {
		_tmp0_ = "off";
	}
	_tmp1_ = g_strconcat ("bluetoothctl power ", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	plank_status_panel_window_run_action (_tmp2_);
	_g_free0 (_tmp2_);
}

static void
___lambda72__plank_status_panel_window_switch_changed (gboolean state,
                                                       gpointer self)
{
	__lambda72_ ((PlankStatusPanelWindow*) self, state);
}

static void
plank_status_panel_window_build_bluetooth (PlankStatusPanelWindow* self)
{
	gboolean powered = FALSE;
	GtkBox* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
	gchar* output = NULL;
	gchar* _tmp3_;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	powered = plank_status_panel_window_contains ("bluetoothctl show", "Powered: yes");
	_tmp0_ = self->priv->content;
	_tmp1_ = plank_status_panel_window_switch_row (self, _ ("Bluetooth"), powered, ___lambda72__plank_status_panel_window_switch_changed, g_object_ref (self), g_object_unref);
	_tmp2_ = _tmp1_;
	gtk_box_pack_start (_tmp0_, _tmp2_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = g_strdup ("");
	output = _tmp3_;
	if (powered) {
		gchar* _tmp5_ = NULL;
		gboolean _tmp6_;
		_tmp6_ = plank_status_panel_window_run ("bluetoothctl devices Paired", &_tmp5_);
		_g_free0 (output);
		output = _tmp5_;
		_tmp4_ = _tmp6_;
	} else {
		_tmp4_ = FALSE;
	}
	if (_tmp4_) {
		const gchar* _tmp7_;
		gchar** _tmp8_;
		gchar** _tmp9_;
		_tmp7_ = output;
		_tmp9_ = _tmp8_ = g_strsplit (_tmp7_, "\n", 0);
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
			line_collection = _tmp9_;
			line_collection_length1 = _vala_array_length (_tmp8_);
			for (line_it = 0; line_it < line_collection_length1; line_it = line_it + 1) {
				const gchar* line = NULL;
				line = line_collection[line_it];
				{
					gchar** fields = NULL;
					const gchar* _tmp10_;
					gchar** _tmp11_;
					gchar** _tmp12_;
					gint fields_length1;
					gint _fields_size_;
					gchar** _tmp13_;
					gint _tmp13__length1;
					_tmp10_ = line;
					_tmp12_ = _tmp11_ = g_strsplit (_tmp10_, " ", 3);
					fields = _tmp12_;
					fields_length1 = _vala_array_length (_tmp11_);
					_fields_size_ = fields_length1;
					_tmp13_ = fields;
					_tmp13__length1 = fields_length1;
					if (_tmp13__length1 >= 3) {
						GtkBox* _tmp14_;
						gchar** _tmp15_;
						gint _tmp15__length1;
						const gchar* _tmp16_;
						GtkWidget* _tmp17_;
						GtkWidget* _tmp18_;
						_tmp14_ = self->priv->content;
						_tmp15_ = fields;
						_tmp15__length1 = fields_length1;
						_tmp16_ = _tmp15_[2];
						_tmp17_ = plank_status_panel_window_info_row (self, _tmp16_, _ ("Paired"));
						_tmp18_ = _tmp17_;
						gtk_box_pack_start (_tmp14_, _tmp18_, FALSE, FALSE, (guint) 0);
						_g_object_unref0 (_tmp18_);
					}
					fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
				}
			}
			line_collection = (_vala_array_free (line_collection, line_collection_length1, (GDestroyNotify) g_free), NULL);
		}
	}
	_g_free0 (output);
}

static void
__lambda73_ (PlankStatusPanelWindow* self,
             gboolean state)
{
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	if (state) {
		_tmp0_ = "on";
	} else {
		_tmp0_ = "off";
	}
	_tmp1_ = g_strconcat ("nmcli radio wifi ", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	plank_status_panel_window_run_action (_tmp2_);
	_g_free0 (_tmp2_);
}

static void
___lambda73__plank_status_panel_window_switch_changed (gboolean state,
                                                       gpointer self)
{
	__lambda73_ ((PlankStatusPanelWindow*) self, state);
}

static void
plank_status_panel_window_build_wifi (PlankStatusPanelWindow* self)
{
	gchar* output = NULL;
	gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	gchar* _tmp2_ = NULL;
	gboolean _tmp3_;
	gboolean enabled = FALSE;
	GtkBox* _tmp7_;
	GtkWidget* _tmp8_;
	GtkWidget* _tmp9_;
	gboolean _tmp10_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	output = _tmp0_;
	_tmp3_ = plank_status_panel_window_run ("nmcli radio wifi", &_tmp2_);
	_g_free0 (output);
	output = _tmp2_;
	if (_tmp3_) {
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp4_ = output;
		_tmp5_ = string_strip (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp1_ = g_strcmp0 (_tmp6_, "enabled") == 0;
		_g_free0 (_tmp6_);
	} else {
		_tmp1_ = FALSE;
	}
	enabled = _tmp1_;
	_tmp7_ = self->priv->content;
	_tmp8_ = plank_status_panel_window_switch_row (self, _ ("Wi-Fi"), enabled, ___lambda73__plank_status_panel_window_switch_changed, g_object_ref (self), g_object_unref);
	_tmp9_ = _tmp8_;
	gtk_box_pack_start (_tmp7_, _tmp9_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp9_);
	if (enabled) {
		gchar* _tmp11_ = NULL;
		gboolean _tmp12_;
		_tmp12_ = plank_status_panel_window_run ("nmcli -t -f IN-USE,SSID,SIGNAL device wifi list --rescan no", &_tmp11_);
		_g_free0 (output);
		output = _tmp11_;
		_tmp10_ = _tmp12_;
	} else {
		_tmp10_ = FALSE;
	}
	if (_tmp10_) {
		gint shown = 0;
		const gchar* _tmp13_;
		gchar** _tmp14_;
		gchar** _tmp15_;
		shown = 0;
		_tmp13_ = output;
		_tmp15_ = _tmp14_ = g_strsplit (_tmp13_, "\n", 0);
		{
			gchar** line_collection = NULL;
			gint line_collection_length1 = 0;
			gint _line_collection_size_ = 0;
			gint line_it = 0;
			line_collection = _tmp15_;
			line_collection_length1 = _vala_array_length (_tmp14_);
			for (line_it = 0; line_it < line_collection_length1; line_it = line_it + 1) {
				const gchar* line = NULL;
				line = line_collection[line_it];
				{
					gchar** fields = NULL;
					const gchar* _tmp16_;
					gchar** _tmp17_;
					gchar** _tmp18_;
					gint fields_length1;
					gint _fields_size_;
					gboolean _tmp19_ = FALSE;
					gboolean _tmp20_ = FALSE;
					gchar** _tmp21_;
					gint _tmp21__length1;
					GtkBox* _tmp25_;
					gchar** _tmp26_;
					gint _tmp26__length1;
					const gchar* _tmp27_;
					gchar** _tmp28_;
					gint _tmp28__length1;
					const gchar* _tmp29_;
					gchar* _tmp30_;
					gchar* _tmp31_;
					GtkWidget* _tmp32_;
					GtkWidget* _tmp33_;
					_tmp16_ = line;
					_tmp18_ = _tmp17_ = g_strsplit (_tmp16_, ":", 0);
					fields = _tmp18_;
					fields_length1 = _vala_array_length (_tmp17_);
					_fields_size_ = fields_length1;
					_tmp21_ = fields;
					_tmp21__length1 = fields_length1;
					if (_tmp21__length1 < 3) {
						_tmp20_ = TRUE;
					} else {
						gchar** _tmp22_;
						gint _tmp22__length1;
						const gchar* _tmp23_;
						_tmp22_ = fields;
						_tmp22__length1 = fields_length1;
						_tmp23_ = _tmp22_[1];
						_tmp20_ = g_strcmp0 (_tmp23_, "") == 0;
					}
					if (_tmp20_) {
						_tmp19_ = TRUE;
					} else {
						gint _tmp24_;
						_tmp24_ = shown;
						shown = _tmp24_ + 1;
						_tmp19_ = _tmp24_ >= 5;
					}
					if (_tmp19_) {
						fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
						continue;
					}
					_tmp25_ = self->priv->content;
					_tmp26_ = fields;
					_tmp26__length1 = fields_length1;
					_tmp27_ = _tmp26_[1];
					_tmp28_ = fields;
					_tmp28__length1 = fields_length1;
					_tmp29_ = _tmp28_[2];
					_tmp30_ = g_strdup_printf (_ ("Signal %s%%"), _tmp29_);
					_tmp31_ = _tmp30_;
					_tmp32_ = plank_status_panel_window_info_row (self, _tmp27_, _tmp31_);
					_tmp33_ = _tmp32_;
					gtk_box_pack_start (_tmp25_, _tmp33_, FALSE, FALSE, (guint) 0);
					_g_object_unref0 (_tmp33_);
					_g_free0 (_tmp31_);
					fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
				}
			}
			line_collection = (_vala_array_free (line_collection, line_collection_length1, (GDestroyNotify) g_free), NULL);
		}
	}
	_g_free0 (output);
}

static void
plank_status_panel_window_build_battery (PlankStatusPanelWindow* self)
{
	gchar* capacity = NULL;
	gchar* _tmp0_;
	gchar* state = NULL;
	gchar* _tmp1_;
	GtkBox* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	GtkWidget* _tmp25_;
	GtkWidget* _tmp26_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("0");
	capacity = _tmp0_;
	_tmp1_ = g_strdup (_ ("Not available"));
	state = _tmp1_;
	{
		GDir* directory = NULL;
		GDir* _tmp2_;
		gchar* name = NULL;
		_tmp2_ = g_dir_open ("/sys/class/power_supply", (guint) 0, &_inner_error0_);
		directory = _tmp2_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_FILE_ERROR) {
				goto __catch0_g_file_error;
			}
			_g_free0 (state);
			_g_free0 (capacity);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		while (TRUE) {
			GDir* _tmp3_;
			const gchar* _tmp4_;
			gchar* _tmp5_;
			const gchar* _tmp6_;
			const gchar* _tmp7_;
			_tmp3_ = directory;
			_tmp4_ = g_dir_read_name (_tmp3_);
			_tmp5_ = g_strdup (_tmp4_);
			_g_free0 (name);
			name = _tmp5_;
			_tmp6_ = name;
			if (!(_tmp6_ != NULL)) {
				break;
			}
			_tmp7_ = name;
			if (g_str_has_prefix (_tmp7_, "BAT")) {
				const gchar* _tmp8_;
				gchar* _tmp9_;
				gchar* _tmp10_;
				gchar* _tmp11_ = NULL;
				const gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* _tmp14_;
				gchar* _tmp15_ = NULL;
				_tmp8_ = name;
				_tmp9_ = g_strdup_printf ("/sys/class/power_supply/%s/capacity", _tmp8_);
				_tmp10_ = _tmp9_;
				g_file_get_contents (_tmp10_, &_tmp11_, NULL, &_inner_error0_);
				_g_free0 (capacity);
				capacity = _tmp11_;
				_g_free0 (_tmp10_);
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					_g_free0 (name);
					_g_dir_close0 (directory);
					if (_inner_error0_->domain == G_FILE_ERROR) {
						goto __catch0_g_file_error;
					}
					_g_free0 (state);
					_g_free0 (capacity);
					g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
					g_clear_error (&_inner_error0_);
					return;
				}
				_tmp12_ = name;
				_tmp13_ = g_strdup_printf ("/sys/class/power_supply/%s/status", _tmp12_);
				_tmp14_ = _tmp13_;
				g_file_get_contents (_tmp14_, &_tmp15_, NULL, &_inner_error0_);
				_g_free0 (state);
				state = _tmp15_;
				_g_free0 (_tmp14_);
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					_g_free0 (name);
					_g_dir_close0 (directory);
					if (_inner_error0_->domain == G_FILE_ERROR) {
						goto __catch0_g_file_error;
					}
					_g_free0 (state);
					_g_free0 (capacity);
					g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
					g_clear_error (&_inner_error0_);
					return;
				}
				break;
			}
		}
		_g_free0 (name);
		_g_dir_close0 (directory);
	}
	goto __finally0;
	__catch0_g_file_error:
	{
		g_clear_error (&_inner_error0_);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (state);
		_g_free0 (capacity);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp16_ = self->priv->content;
	_tmp17_ = capacity;
	_tmp18_ = string_strip (_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strdup_printf (_ ("%s%% remaining"), _tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = state;
	_tmp23_ = string_strip (_tmp22_);
	_tmp24_ = _tmp23_;
	_tmp25_ = plank_status_panel_window_info_row (self, _tmp21_, _tmp24_);
	_tmp26_ = _tmp25_;
	gtk_box_pack_start (_tmp16_, _tmp26_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp26_);
	_g_free0 (_tmp24_);
	_g_free0 (_tmp21_);
	_g_free0 (_tmp19_);
	_g_free0 (state);
	_g_free0 (capacity);
}

static void
plank_status_panel_window_build_clock (PlankStatusPanelWindow* self)
{
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	GtkBox* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GtkWidget* _tmp6_;
	GtkWidget* _tmp7_;
	GtkCalendar* calendar = NULL;
	GtkCalendar* _tmp8_;
	GtkBox* _tmp9_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_local ();
	now = _tmp0_;
	_tmp1_ = self->priv->content;
	_tmp2_ = g_date_time_format (now, "%H:%M");
	_tmp3_ = _tmp2_;
	_tmp4_ = g_date_time_format (now, "%A, %e %B");
	_tmp5_ = _tmp4_;
	_tmp6_ = plank_status_panel_window_info_row (self, _tmp3_, _tmp5_);
	_tmp7_ = _tmp6_;
	gtk_box_pack_start (_tmp1_, _tmp7_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	_tmp8_ = (GtkCalendar*) gtk_calendar_new ();
	g_object_ref_sink (_tmp8_);
	calendar = _tmp8_;
	g_object_set (calendar, "show-heading", TRUE, NULL);
	g_object_set (calendar, "show-day-names", TRUE, NULL);
	_tmp9_ = self->priv->content;
	gtk_box_pack_start (_tmp9_, (GtkWidget*) calendar, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (calendar);
	_g_date_time_unref0 (now);
}

static Block30Data*
block30_data_ref (Block30Data* _data30_)
{
	g_atomic_int_inc (&_data30_->_ref_count_);
	return _data30_;
}

static void
block30_data_unref (void * _userdata_)
{
	Block30Data* _data30_;
	_data30_ = (Block30Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data30_->_ref_count_)) {
		PlankStatusPanelWindow* self;
		self = _data30_->self;
		_g_object_unref0 (_data30_->toggle);
		(_data30_->changed_target_destroy_notify == NULL) ? NULL : (_data30_->changed_target_destroy_notify (_data30_->changed_target), NULL);
		_data30_->changed = NULL;
		_data30_->changed_target = NULL;
		_data30_->changed_target_destroy_notify = NULL;
		_g_object_unref0 (self);
		g_slice_free (Block30Data, _data30_);
	}
}

static void
__lambda71_ (Block30Data* _data30_)
{
	PlankStatusPanelWindow* self;
	gboolean _tmp0_;
	gboolean _tmp1_;
	self = _data30_->self;
	_tmp0_ = gtk_switch_get_active (_data30_->toggle);
	_tmp1_ = _tmp0_;
	_data30_->changed (_tmp1_, _data30_->changed_target);
}

static void
___lambda71__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
	__lambda71_ (self);
}

static GtkWidget*
plank_status_panel_window_switch_row (PlankStatusPanelWindow* self,
                                      const gchar* label,
                                      gboolean state,
                                      PlankStatusPanelWindowSwitchChanged changed,
                                      gpointer changed_target,
                                      GDestroyNotify changed_target_destroy_notify)
{
	Block30Data* _data30_;
	GtkBox* row = NULL;
	GtkBox* _tmp0_;
	GtkStyleContext* _tmp1_;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_;
	GtkSwitch* _tmp4_ = NULL;
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (label != NULL, NULL);
	_data30_ = g_slice_new0 (Block30Data);
	_data30_->_ref_count_ = 1;
	_data30_->self = g_object_ref (self);
	(_data30_->changed_target_destroy_notify == NULL) ? NULL : (_data30_->changed_target_destroy_notify (_data30_->changed_target), NULL);
	_data30_->changed = NULL;
	_data30_->changed_target = NULL;
	_data30_->changed_target_destroy_notify = NULL;
	_data30_->changed = changed;
	_data30_->changed_target = changed_target;
	_data30_->changed_target_destroy_notify = changed_target_destroy_notify;
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 10);
	g_object_ref_sink (_tmp0_);
	row = _tmp0_;
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) row);
	gtk_style_context_add_class (_tmp1_, "status-row");
	_tmp2_ = (GtkLabel*) gtk_label_new (label);
	gtk_label_set_xalign (_tmp2_, 0.0f);
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	gtk_box_pack_start (row, (GtkWidget*) _tmp3_, TRUE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp3_);
	_tmp4_ = (GtkSwitch*) gtk_switch_new ();
	gtk_switch_set_active (_tmp4_, state);
	gtk_widget_set_valign ((GtkWidget*) _tmp4_, GTK_ALIGN_CENTER);
	g_object_ref_sink (_tmp4_);
	_data30_->toggle = _tmp4_;
	g_signal_connect_data ((GObject*) _data30_->toggle, "notify::active", (GCallback) ___lambda71__g_object_notify, block30_data_ref (_data30_), (GClosureNotify) block30_data_unref, 0);
	gtk_box_pack_end (row, (GtkWidget*) _data30_->toggle, FALSE, FALSE, (guint) 0);
	result = (GtkWidget*) row;
	block30_data_unref (_data30_);
	_data30_ = NULL;
	return result;
}

static GtkWidget*
plank_status_panel_window_info_row (PlankStatusPanelWindow* self,
                                    const gchar* title,
                                    const gchar* subtitle)
{
	GtkBox* row = NULL;
	GtkBox* _tmp0_;
	GtkStyleContext* _tmp1_;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_;
	GtkLabel* sub = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_;
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (title != NULL, NULL);
	g_return_val_if_fail (subtitle != NULL, NULL);
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 2);
	g_object_ref_sink (_tmp0_);
	row = _tmp0_;
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) row);
	gtk_style_context_add_class (_tmp1_, "status-row");
	_tmp2_ = (GtkLabel*) gtk_label_new (title);
	gtk_label_set_xalign (_tmp2_, 0.0f);
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	gtk_box_pack_start (row, (GtkWidget*) _tmp3_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp3_);
	_tmp4_ = (GtkLabel*) gtk_label_new (subtitle);
	gtk_label_set_xalign (_tmp4_, 0.0f);
	g_object_ref_sink (_tmp4_);
	sub = _tmp4_;
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) sub);
	gtk_style_context_add_class (_tmp5_, GTK_STYLE_CLASS_DIM_LABEL);
	gtk_box_pack_start (row, (GtkWidget*) sub, FALSE, FALSE, (guint) 0);
	result = (GtkWidget*) row;
	_g_object_unref0 (sub);
	return result;
}

static void
plank_status_panel_window_position_over_item (PlankStatusPanelWindow* self)
{
	PlankStatusIndicatorItem* _tmp0_;
	GdkRectangle item = {0};
	PlankDockController* _tmp1_;
	PlankPositionManager* _tmp2_;
	PlankPositionManager* _tmp3_;
	PlankStatusIndicatorItem* _tmp4_;
	GdkRectangle _tmp5_ = {0};
	GdkRectangle bar = {0};
	PlankDockController* _tmp6_;
	PlankPositionManager* _tmp7_;
	PlankPositionManager* _tmp8_;
	GdkRectangle _tmp9_ = {0};
	GdkRectangle workarea = {0};
	GdkRectangle _tmp10_ = {0};
	gint actual_width = 0;
	gint actual_height = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	gint desired_x = 0;
	GdkRectangle _tmp13_;
	GdkRectangle _tmp14_;
	gint min_x = 0;
	GdkRectangle _tmp15_;
	gint max_x = 0;
	GdkRectangle _tmp16_;
	GdkRectangle _tmp17_;
	gint desired_y = 0;
	GdkRectangle _tmp18_;
	gint min_y = 0;
	GdkRectangle _tmp19_;
	gint max_y = 0;
	GdkRectangle _tmp20_;
	GdkRectangle _tmp21_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->current_item;
	if (_tmp0_ == NULL) {
		return;
	}
	_tmp1_ = self->priv->controller;
	_tmp2_ = plank_dock_controller_get_position_manager (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = self->priv->current_item;
	plank_position_manager_get_screen_region_for_item (_tmp3_, (PlankDockItem*) _tmp4_, &_tmp5_);
	item = _tmp5_;
	_tmp6_ = self->priv->controller;
	_tmp7_ = plank_dock_controller_get_position_manager (_tmp6_);
	_tmp8_ = _tmp7_;
	plank_position_manager_get_screen_background_region (_tmp8_, &_tmp9_);
	bar = _tmp9_;
	plank_status_panel_window_active_workarea (self, &_tmp10_);
	workarea = _tmp10_;
	gtk_window_get_size ((GtkWindow*) self, &_tmp11_, &_tmp12_);
	actual_width = _tmp11_;
	actual_height = _tmp12_;
	_tmp13_ = item;
	_tmp14_ = item;
	desired_x = (_tmp13_.x + (_tmp14_.width / 2)) - (actual_width / 2);
	_tmp15_ = workarea;
	min_x = _tmp15_.x + 8;
	_tmp16_ = workarea;
	_tmp17_ = workarea;
	max_x = ((_tmp16_.x + _tmp17_.width) - actual_width) - 8;
	_tmp18_ = bar;
	desired_y = (_tmp18_.y - actual_height) - PLANK_STATUS_PANEL_WINDOW_PANEL_GAP;
	_tmp19_ = workarea;
	min_y = _tmp19_.y + 8;
	_tmp20_ = workarea;
	_tmp21_ = workarea;
	max_y = ((_tmp20_.y + _tmp21_.height) - actual_height) - 8;
	gtk_window_move ((GtkWindow*) self, MAX (min_x, MIN (max_x, desired_x)), MAX (min_y, MIN (max_y, desired_y)));
}

static void
plank_status_panel_window_active_workarea (PlankStatusPanelWindow* self,
                                           GdkRectangle* result)
{
	GdkScreen* screen = NULL;
	GdkScreen* _tmp0_;
	GdkScreen* _tmp1_;
	GdkRectangle bar = {0};
	PlankDockController* _tmp2_;
	PlankPositionManager* _tmp3_;
	PlankPositionManager* _tmp4_;
	GdkRectangle _tmp5_ = {0};
	gint monitor = 0;
	GdkRectangle _tmp6_;
	GdkRectangle _tmp7_;
	GdkRectangle _tmp8_;
	GdkRectangle _tmp9_;
	GdkRectangle _tmp10_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	screen = _tmp1_;
	_tmp2_ = self->priv->controller;
	_tmp3_ = plank_dock_controller_get_position_manager (_tmp2_);
	_tmp4_ = _tmp3_;
	plank_position_manager_get_screen_background_region (_tmp4_, &_tmp5_);
	bar = _tmp5_;
	_tmp6_ = bar;
	_tmp7_ = bar;
	_tmp8_ = bar;
	_tmp9_ = bar;
	monitor = gdk_screen_get_monitor_at_point (screen, _tmp6_.x + (_tmp7_.width / 2), _tmp8_.y + (_tmp9_.height / 2));
	gdk_screen_get_monitor_workarea (screen, monitor, &_tmp10_);
	*result = _tmp10_;
	_g_object_unref0 (screen);
	return;
}

static void
plank_status_panel_window_apply_theme (PlankStatusPanelWindow* self)
{
	PlankColor color = {0};
	PlankDockController* _tmp0_;
	PlankDockRenderer* _tmp1_;
	PlankDockRenderer* _tmp2_;
	PlankDockTheme* _tmp3_;
	PlankDockTheme* _tmp4_;
	PlankColor _tmp5_ = {0};
	PlankColor _tmp6_;
	gchar* css = NULL;
	gchar* _tmp7_;
	const gchar* _tmp8_;
	PlankColor _tmp9_;
	PlankColor _tmp10_;
	PlankColor _tmp11_;
	PlankColor _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	const gchar* _tmp20_;
	gchar* _tmp21_;
	const gchar* _tmp22_;
	gchar* _tmp23_;
	const gchar* _tmp24_;
	gchar* _tmp25_;
	const gchar* _tmp26_;
	gchar* _tmp27_;
	const gchar* _tmp28_;
	gchar* _tmp29_;
	const gchar* _tmp30_;
	gchar* _tmp31_;
	const gchar* _tmp32_;
	gchar* _tmp33_;
	const gchar* _tmp34_;
	gchar* _tmp35_;
	const gchar* _tmp36_;
	gchar* _tmp37_;
	const gchar* _tmp38_;
	gchar* _tmp39_;
	const gchar* _tmp40_;
	gchar* _tmp41_;
	const gchar* _tmp42_;
	gchar* _tmp43_;
	const gchar* _tmp44_;
	gchar* _tmp45_;
	const gchar* _tmp46_;
	gchar* _tmp47_;
	const gchar* _tmp48_;
	gchar* _tmp49_;
	const gchar* _tmp50_;
	gchar* _tmp51_;
	const gchar* _tmp52_;
	gchar* _tmp53_;
	const gchar* _tmp54_;
	gchar* _tmp55_;
	const gchar* _tmp56_;
	gchar* _tmp57_;
	GtkCssProvider* _tmp58_;
	GtkCssProvider* _tmp61_;
	GdkScreen* _tmp66_;
	GtkCssProvider* _tmp67_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->controller;
	_tmp1_ = plank_dock_controller_get_renderer (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = plank_dock_renderer_get_theme (_tmp2_);
	_tmp4_ = _tmp3_;
	plank_theme_get_FillStartColor ((PlankTheme*) _tmp4_, &_tmp5_);
	_tmp6_ = _tmp5_;
	color = _tmp6_;
	_tmp7_ = g_strdup (".plank-status-panel { background: transparent; }");
	css = _tmp7_;
	_tmp8_ = css;
	_tmp9_ = color;
	_tmp10_ = color;
	_tmp11_ = color;
	_tmp12_ = color;
	_tmp13_ = g_strdup_printf (".plank-status-panel .status-card { background-color: rgba(%d,%d,%d,%.3" \
"f); border: 1px solid rgba(255,255,255,0.10); border-radius: 12px; pad" \
"ding: 7px; }", (gint) (_tmp9_.red * 255), (gint) (_tmp10_.green * 255), (gint) (_tmp11_.blue * 255), _tmp12_.alpha);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp8_, _tmp14_, NULL);
	_g_free0 (css);
	css = _tmp15_;
	_g_free0 (_tmp14_);
	_tmp16_ = css;
	_tmp17_ = g_strconcat (_tmp16_, ".plank-status-panel .status-title { padding: 5px 7px; color: white; }", NULL);
	_g_free0 (css);
	css = _tmp17_;
	_tmp18_ = css;
	_tmp19_ = g_strconcat (_tmp18_, ".plank-status-panel .status-title-label { font-weight: bold; font-size" \
": 15px; }", NULL);
	_g_free0 (css);
	css = _tmp19_;
	_tmp20_ = css;
	_tmp21_ = g_strconcat (_tmp20_, ".plank-status-panel .status-row { color: white; padding: 4px 6px; bord" \
"er-radius: 8px; }", NULL);
	_g_free0 (css);
	css = _tmp21_;
	_tmp22_ = css;
	_tmp23_ = g_strconcat (_tmp22_, ".plank-status-panel .status-section-label { color: rgba(255,255,255,0." \
"58); font-size: 10px; font-weight: bold; margin: 4px 6px 0 6px; }", NULL);
	_g_free0 (css);
	css = _tmp23_;
	_tmp24_ = css;
	_tmp25_ = g_strconcat (_tmp24_, ".plank-status-panel .status-action-button { color: white; background-c" \
"olor: rgba(255,255,255,0.08); background-image: none; border: none; bo" \
"rder-radius: 8px; box-shadow: none; padding: 5px; margin-top: 4px; }", NULL);
	_g_free0 (css);
	css = _tmp25_;
	_tmp26_ = css;
	_tmp27_ = g_strconcat (_tmp26_, ".plank-status-panel .status-footer { padding-top: 4px; }", NULL);
	_g_free0 (css);
	css = _tmp27_;
	_tmp28_ = css;
	_tmp29_ = g_strconcat (_tmp28_, ".plank-status-panel .status-icon-toggle { color: rgba(255,255,255,0.65" \
"); background: transparent; background-image: none; border: none; bord" \
"er-radius: 7px; box-shadow: none; padding: 5px; }", NULL);
	_g_free0 (css);
	css = _tmp29_;
	_tmp30_ = css;
	_tmp31_ = g_strconcat (_tmp30_, ".plank-status-panel .status-icon-toggle:checked { color: white; backgr" \
"ound-color: rgba(255,255,255,0.14); }", NULL);
	_g_free0 (css);
	css = _tmp31_;
	_tmp32_ = css;
	_tmp33_ = g_strconcat (_tmp32_, ".plank-status-panel .modern-volume-bar { margin: 2px 6px 5px 6px; }", NULL);
	_g_free0 (css);
	css = _tmp33_;
	_tmp34_ = css;
	_tmp35_ = g_strconcat (_tmp34_, ".plank-status-panel .modern-volume-scale trough { min-height: 36px; ba" \
"ckground-color: rgba(255,255,255,0.08); border: 1px solid rgba(255,255" \
",255,0.08); border-radius: 10px; }", NULL);
	_g_free0 (css);
	css = _tmp35_;
	_tmp36_ = css;
	_tmp37_ = g_strconcat (_tmp36_, ".plank-status-panel .modern-volume-scale highlight { background-color:" \
" rgba(115,210,22,0.48); border-radius: 9px; }", NULL);
	_g_free0 (css);
	css = _tmp37_;
	_tmp38_ = css;
	_tmp39_ = g_strconcat (_tmp38_, ".plank-status-panel .modern-volume-scale slider { min-width: 0; min-he" \
"ight: 0; margin: 0; padding: 0; background: transparent; border: none;" \
" box-shadow: none; }", NULL);
	_g_free0 (css);
	css = _tmp39_;
	_tmp40_ = css;
	_tmp41_ = g_strconcat (_tmp40_, ".plank-status-panel .modern-volume-bar .status-icon-toggle { color: wh" \
"ite; background: transparent; padding: 5px; }", NULL);
	_g_free0 (css);
	css = _tmp41_;
	_tmp42_ = css;
	_tmp43_ = g_strconcat (_tmp42_, ".plank-status-panel .modern-volume-value { color: white; font-size: 11" \
"px; font-weight: bold; }", NULL);
	_g_free0 (css);
	css = _tmp43_;
	_tmp44_ = css;
	_tmp45_ = g_strconcat (_tmp44_, ".plank-status-panel .modern-device-selector { color: white; background" \
": transparent; border: none; box-shadow: none; padding: 0; }", NULL);
	_g_free0 (css);
	css = _tmp45_;
	_tmp46_ = css;
	_tmp47_ = g_strconcat (_tmp46_, ".plank-status-panel .modern-device-selector button { color: white; bac" \
"kground-color: rgba(255,255,255,0.07); background-image: none; border:" \
" 1px solid rgba(255,255,255,0.09); border-radius: 9px; box-shadow: non" \
"e; padding: 6px 9px; }", NULL);
	_g_free0 (css);
	css = _tmp47_;
	_tmp48_ = css;
	_tmp49_ = g_strconcat (_tmp48_, ".plank-status-panel .modern-device-selector button:hover { background-" \
"color: rgba(255,255,255,0.11); }", NULL);
	_g_free0 (css);
	css = _tmp49_;
	_tmp50_ = css;
	_tmp51_ = g_strconcat (_tmp50_, ".plank-status-panel separator { background-color: rgba(255,255,255,0.1" \
"0); }", NULL);
	_g_free0 (css);
	css = _tmp51_;
	_tmp52_ = css;
	_tmp53_ = g_strconcat (_tmp52_, ".plank-status-panel .status-scroll { background: transparent; border: " \
"none; box-shadow: none; }", NULL);
	_g_free0 (css);
	css = _tmp53_;
	_tmp54_ = css;
	_tmp55_ = g_strconcat (_tmp54_, ".plank-status-panel scrollbar { background: transparent; border: none;" \
" }", NULL);
	_g_free0 (css);
	css = _tmp55_;
	_tmp56_ = css;
	_tmp57_ = g_strconcat (_tmp56_, ".plank-status-panel scrollbar slider { min-width: 4px; min-height: 28p" \
"x; background-color: rgba(255,255,255,0.18); border-radius: 4px; }", NULL);
	_g_free0 (css);
	css = _tmp57_;
	_tmp58_ = self->priv->css_provider;
	if (_tmp58_ != NULL) {
		GdkScreen* _tmp59_;
		GtkCssProvider* _tmp60_;
		_tmp59_ = gtk_window_get_screen ((GtkWindow*) self);
		_tmp60_ = self->priv->css_provider;
		gtk_style_context_remove_provider_for_screen (_tmp59_, (GtkStyleProvider*) _tmp60_);
	}
	_tmp61_ = gtk_css_provider_new ();
	_g_object_unref0 (self->priv->css_provider);
	self->priv->css_provider = _tmp61_;
	{
		GtkCssProvider* _tmp62_;
		const gchar* _tmp63_;
		_tmp62_ = self->priv->css_provider;
		_tmp63_ = css;
		gtk_css_provider_load_from_data (_tmp62_, _tmp63_, (gssize) -1, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp64_;
		const gchar* _tmp65_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp64_ = e;
		_tmp65_ = _tmp64_->message;
		g_warning ("StatusPanelWindow.vala:462: Status panel CSS: %s", _tmp65_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (css);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp66_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp67_ = self->priv->css_provider;
	gtk_style_context_add_provider_for_screen (_tmp66_, (GtkStyleProvider*) _tmp67_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
	_g_free0 (css);
}

static gboolean
plank_status_panel_window_run (const gchar* command,
                               gchar** output)
{
	gchar* _vala_output = NULL;
	gchar* _error_ = NULL;
	gint status = 0;
	gboolean _tmp5_ = FALSE;
	GError* _inner_error0_ = NULL;
	gboolean result;
	g_return_val_if_fail (command != NULL, FALSE);
	{
		gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gint _tmp2_ = 0;
		g_spawn_command_line_sync (command, &_tmp0_, &_tmp1_, &_tmp2_, &_inner_error0_);
		_g_free0 (_vala_output);
		_vala_output = _tmp0_;
		_g_free0 (_error_);
		_error_ = _tmp1_;
		status = _tmp2_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gboolean _tmp3_ = FALSE;
			if (_inner_error0_->domain == G_SPAWN_ERROR) {
				goto __catch0_g_spawn_error;
			}
			_g_free0 (_error_);
			_g_free0 (_vala_output);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp3_;
		}
		result = status == 0;
		_g_free0 (_error_);
		if (output) {
			*output = _vala_output;
		} else {
			_g_free0 (_vala_output);
		}
		return result;
	}
	goto __finally0;
	__catch0_g_spawn_error:
	{
		gchar* _tmp4_;
		g_clear_error (&_inner_error0_);
		_tmp4_ = g_strdup ("");
		_g_free0 (_vala_output);
		_vala_output = _tmp4_;
		result = FALSE;
		_g_free0 (_error_);
		if (output) {
			*output = _vala_output;
		} else {
			_g_free0 (_vala_output);
		}
		return result;
	}
	__finally0:
	_g_free0 (_error_);
	_g_free0 (_vala_output);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return _tmp5_;
}

static void
plank_status_panel_window_run_action (const gchar* command)
{
	gchar* output = NULL;
	gchar* _tmp0_ = NULL;
	g_return_if_fail (command != NULL);
	plank_status_panel_window_run (command, &_tmp0_);
	_g_free0 (output);
	output = _tmp0_;
	_g_free0 (output);
}

static void
plank_status_panel_window_launch (const gchar* command)
{
	GError* _inner_error0_ = NULL;
	g_return_if_fail (command != NULL);
	{
		g_spawn_command_line_async (command, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_SPAWN_ERROR) {
				goto __catch0_g_spawn_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
	}
	goto __finally0;
	__catch0_g_spawn_error:
	{
		g_clear_error (&_inner_error0_);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

static gboolean
plank_status_panel_window_contains (const gchar* command,
                                    const gchar* needle)
{
	gchar* output = NULL;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_;
	gboolean result;
	g_return_val_if_fail (command != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp2_ = plank_status_panel_window_run (command, &_tmp1_);
	_g_free0 (output);
	output = _tmp1_;
	if (_tmp2_) {
		const gchar* _tmp3_;
		_tmp3_ = output;
		_tmp0_ = string_contains (_tmp3_, needle);
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	_g_free0 (output);
	return result;
}

static gchar*
plank_status_panel_window_label_for_kind (PlankStatusIndicatorKind kind)
{
	gchar* result;
	switch (kind) {
		case PLANK_STATUS_INDICATOR_KIND_VOLUME:
		{
			gchar* _tmp0_;
			_tmp0_ = g_strdup (_ ("Volume"));
			result = _tmp0_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_BLUETOOTH:
		{
			gchar* _tmp1_;
			_tmp1_ = g_strdup (_ ("Bluetooth"));
			result = _tmp1_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_WIFI:
		{
			gchar* _tmp2_;
			_tmp2_ = g_strdup (_ ("Wi-Fi"));
			result = _tmp2_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_BATTERY:
		{
			gchar* _tmp3_;
			_tmp3_ = g_strdup (_ ("Battery"));
			result = _tmp3_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_CLOCK:
		{
			gchar* _tmp4_;
			_tmp4_ = g_strdup (_ ("Time and date"));
			result = _tmp4_;
			return result;
		}
		default:
		{
			gchar* _tmp5_;
			_tmp5_ = g_strdup ("");
			result = _tmp5_;
			return result;
		}
	}
}

static gchar*
plank_status_panel_window_icon_for_kind (PlankStatusIndicatorKind kind)
{
	gchar* result;
	switch (kind) {
		case PLANK_STATUS_INDICATOR_KIND_VOLUME:
		{
			gchar* _tmp0_;
			_tmp0_ = g_strdup ("audio-volume-high-symbolic");
			result = _tmp0_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_BLUETOOTH:
		{
			gchar* _tmp1_;
			_tmp1_ = g_strdup ("bluetooth-symbolic");
			result = _tmp1_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_WIFI:
		{
			gchar* _tmp2_;
			_tmp2_ = g_strdup ("network-wireless-symbolic");
			result = _tmp2_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_BATTERY:
		{
			gchar* _tmp3_;
			_tmp3_ = g_strdup ("battery-good-symbolic");
			result = _tmp3_;
			return result;
		}
		case PLANK_STATUS_INDICATOR_KIND_CLOCK:
		{
			gchar* _tmp4_;
			_tmp4_ = g_strdup ("preferences-system-time-symbolic");
			result = _tmp4_;
			return result;
		}
		default:
		{
			gchar* _tmp5_;
			_tmp5_ = g_strdup ("preferences-system-symbolic");
			result = _tmp5_;
			return result;
		}
	}
}

static void
plank_status_panel_window_class_init (PlankStatusPanelWindowClass * klass,
                                      gpointer klass_data)
{
	plank_status_panel_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &PlankStatusPanelWindow_private_offset);
	G_OBJECT_CLASS (klass)->finalize = plank_status_panel_window_finalize;
}

static void
plank_status_panel_window_instance_init (PlankStatusPanelWindow * self,
                                         gpointer klass)
{
	self->priv = plank_status_panel_window_get_instance_private (self);
	self->priv->active_panel_width = PLANK_STATUS_PANEL_WINDOW_PANEL_WIDTH;
	self->priv->active_panel_height = PLANK_STATUS_PANEL_WINDOW_PANEL_HEIGHT;
	self->priv->device_popup_open = FALSE;
}

static void
plank_status_panel_window_finalize (GObject * obj)
{
	PlankStatusPanelWindow * self;
	GtkCssProvider* _tmp0_;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLANK_TYPE_STATUS_PANEL_WINDOW, PlankStatusPanelWindow);
	_tmp0_ = self->priv->css_provider;
	if (_tmp0_ != NULL) {
		GdkScreen* _tmp1_;
		GtkCssProvider* _tmp2_;
		_tmp1_ = gtk_window_get_screen ((GtkWindow*) self);
		_tmp2_ = self->priv->css_provider;
		gtk_style_context_remove_provider_for_screen (_tmp1_, (GtkStyleProvider*) _tmp2_);
	}
	_g_object_unref0 (self->priv->content);
	_g_object_unref0 (self->priv->footer);
	_g_object_unref0 (self->priv->current_item);
	_g_object_unref0 (self->priv->css_provider);
	G_OBJECT_CLASS (plank_status_panel_window_parent_class)->finalize (obj);
}

static GType
plank_status_panel_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (PlankStatusPanelWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) plank_status_panel_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlankStatusPanelWindow), 0, (GInstanceInitFunc) plank_status_panel_window_instance_init, NULL };
	GType plank_status_panel_window_type_id;
	plank_status_panel_window_type_id = g_type_register_static (gtk_window_get_type (), "PlankStatusPanelWindow", &g_define_type_info, 0);
	PlankStatusPanelWindow_private_offset = g_type_add_instance_private (plank_status_panel_window_type_id, sizeof (PlankStatusPanelWindowPrivate));
	return plank_status_panel_window_type_id;
}

GType
plank_status_panel_window_get_type (void)
{
	static volatile gsize plank_status_panel_window_type_id__once = 0;
	if (g_once_init_enter (&plank_status_panel_window_type_id__once)) {
		GType plank_status_panel_window_type_id;
		plank_status_panel_window_type_id = plank_status_panel_window_get_type_once ();
		g_once_init_leave (&plank_status_panel_window_type_id__once, plank_status_panel_window_type_id);
	}
	return plank_status_panel_window_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

