/* CPUMonitorDocklet.c generated by valac 0.56.16, the Vala compiler
 * generated from CPUMonitorDocklet.vala, do not modify */

/**/
/*  Copyright (C) 2016 Rico Tzschichholz*/
/**/
/*  This file is part of Plank.*/
/**/
/*  Plank is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  Plank is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <plank.h>
#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define DOCKY_TYPE_CPU_MONITOR_DOCKLET (docky_cpu_monitor_docklet_get_type ())
#define DOCKY_CPU_MONITOR_DOCKLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOCKY_TYPE_CPU_MONITOR_DOCKLET, DockyCPUMonitorDocklet))
#define DOCKY_CPU_MONITOR_DOCKLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOCKY_TYPE_CPU_MONITOR_DOCKLET, DockyCPUMonitorDockletClass))
#define DOCKY_IS_CPU_MONITOR_DOCKLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOCKY_TYPE_CPU_MONITOR_DOCKLET))
#define DOCKY_IS_CPU_MONITOR_DOCKLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOCKY_TYPE_CPU_MONITOR_DOCKLET))
#define DOCKY_CPU_MONITOR_DOCKLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOCKY_TYPE_CPU_MONITOR_DOCKLET, DockyCPUMonitorDockletClass))

typedef struct _DockyCPUMonitorDocklet DockyCPUMonitorDocklet;
typedef struct _DockyCPUMonitorDockletClass DockyCPUMonitorDockletClass;
typedef struct _DockyCPUMonitorDockletPrivate DockyCPUMonitorDockletPrivate;
enum  {
	DOCKY_CPU_MONITOR_DOCKLET_0_PROPERTY,
	DOCKY_CPU_MONITOR_DOCKLET_NUM_PROPERTIES
};
static GParamSpec* docky_cpu_monitor_docklet_properties[DOCKY_CPU_MONITOR_DOCKLET_NUM_PROPERTIES];

#define DOCKY_TYPE_CPU_MONITOR_DOCK_ITEM (docky_cpu_monitor_dock_item_get_type ())
#define DOCKY_CPU_MONITOR_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOCKY_TYPE_CPU_MONITOR_DOCK_ITEM, DockyCPUMonitorDockItem))
#define DOCKY_CPU_MONITOR_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOCKY_TYPE_CPU_MONITOR_DOCK_ITEM, DockyCPUMonitorDockItemClass))
#define DOCKY_IS_CPU_MONITOR_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOCKY_TYPE_CPU_MONITOR_DOCK_ITEM))
#define DOCKY_IS_CPU_MONITOR_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOCKY_TYPE_CPU_MONITOR_DOCK_ITEM))
#define DOCKY_CPU_MONITOR_DOCK_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOCKY_TYPE_CPU_MONITOR_DOCK_ITEM, DockyCPUMonitorDockItemClass))

typedef struct _DockyCPUMonitorDockItem DockyCPUMonitorDockItem;
typedef struct _DockyCPUMonitorDockItemClass DockyCPUMonitorDockItemClass;

struct _DockyCPUMonitorDocklet {
	GObject parent_instance;
	DockyCPUMonitorDockletPrivate * priv;
};

struct _DockyCPUMonitorDockletClass {
	GObjectClass parent_class;
};

static gpointer docky_cpu_monitor_docklet_parent_class = NULL;
static PlankDockletIface * docky_cpu_monitor_docklet_plank_docklet_parent_iface = NULL;

VALA_EXTERN void docklet_init (PlankDockletManager* manager);
VALA_EXTERN GType docky_cpu_monitor_docklet_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DockyCPUMonitorDocklet, g_object_unref)
static const gchar* docky_cpu_monitor_docklet_real_get_id (PlankDocklet* base);
static const gchar* docky_cpu_monitor_docklet_real_get_name (PlankDocklet* base);
static const gchar* docky_cpu_monitor_docklet_real_get_description (PlankDocklet* base);
static const gchar* docky_cpu_monitor_docklet_real_get_icon (PlankDocklet* base);
static gboolean docky_cpu_monitor_docklet_real_is_supported (PlankDocklet* base);
static PlankDockElement* docky_cpu_monitor_docklet_real_make_element (PlankDocklet* base,
                                                               const gchar* launcher,
                                                               GFile* file);
VALA_EXTERN DockyCPUMonitorDockItem* docky_cpu_monitor_dock_item_new_with_dockitem_file (GFile* file);
VALA_EXTERN DockyCPUMonitorDockItem* docky_cpu_monitor_dock_item_construct_with_dockitem_file (GType object_type,
                                                                                   GFile* file);
VALA_EXTERN GType docky_cpu_monitor_dock_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DockyCPUMonitorDockItem, g_object_unref)
VALA_EXTERN DockyCPUMonitorDocklet* docky_cpu_monitor_docklet_new (void);
VALA_EXTERN DockyCPUMonitorDocklet* docky_cpu_monitor_docklet_construct (GType object_type);
static GType docky_cpu_monitor_docklet_get_type_once (void);

void
docklet_init (PlankDockletManager* manager)
{
	g_return_if_fail (manager != NULL);
	plank_docklet_manager_register_docklet (manager, DOCKY_TYPE_CPU_MONITOR_DOCKLET);
}

static const gchar*
docky_cpu_monitor_docklet_real_get_id (PlankDocklet* base)
{
	DockyCPUMonitorDocklet * self;
	const gchar* result;
	self = (DockyCPUMonitorDocklet*) base;
	result = "cpumonitor";
	return result;
}

static const gchar*
docky_cpu_monitor_docklet_real_get_name (PlankDocklet* base)
{
	DockyCPUMonitorDocklet * self;
	const gchar* result;
	self = (DockyCPUMonitorDocklet*) base;
	result = _ ("CPU Monitor");
	return result;
}

static const gchar*
docky_cpu_monitor_docklet_real_get_description (PlankDocklet* base)
{
	DockyCPUMonitorDocklet * self;
	const gchar* result;
	self = (DockyCPUMonitorDocklet*) base;
	result = _ ("Keep an eye on that CPU. And when it gets out of line...");
	return result;
}

static const gchar*
docky_cpu_monitor_docklet_real_get_icon (PlankDocklet* base)
{
	DockyCPUMonitorDocklet * self;
	const gchar* result;
	self = (DockyCPUMonitorDocklet*) base;
	result = "application-x-addon";
	return result;
}

static gboolean
docky_cpu_monitor_docklet_real_is_supported (PlankDocklet* base)
{
	DockyCPUMonitorDocklet * self;
	gboolean result;
	self = (DockyCPUMonitorDocklet*) base;
	result = TRUE;
	return result;
}

static PlankDockElement*
docky_cpu_monitor_docklet_real_make_element (PlankDocklet* base,
                                             const gchar* launcher,
                                             GFile* file)
{
	DockyCPUMonitorDocklet * self;
	DockyCPUMonitorDockItem* _tmp0_;
	PlankDockElement* result;
	self = (DockyCPUMonitorDocklet*) base;
	g_return_val_if_fail (launcher != NULL, NULL);
	g_return_val_if_fail (file != NULL, NULL);
	_tmp0_ = docky_cpu_monitor_dock_item_new_with_dockitem_file (file);
	result = (PlankDockElement*) _tmp0_;
	return result;
}

DockyCPUMonitorDocklet*
docky_cpu_monitor_docklet_construct (GType object_type)
{
	DockyCPUMonitorDocklet * self = NULL;
	self = (DockyCPUMonitorDocklet*) g_object_new (object_type, NULL);
	return self;
}

DockyCPUMonitorDocklet*
docky_cpu_monitor_docklet_new (void)
{
	return docky_cpu_monitor_docklet_construct (DOCKY_TYPE_CPU_MONITOR_DOCKLET);
}

static void
docky_cpu_monitor_docklet_class_init (DockyCPUMonitorDockletClass * klass,
                                      gpointer klass_data)
{
	docky_cpu_monitor_docklet_parent_class = g_type_class_peek_parent (klass);
}

static void
docky_cpu_monitor_docklet_plank_docklet_interface_init (PlankDockletIface * iface,
                                                        gpointer iface_data)
{
	docky_cpu_monitor_docklet_plank_docklet_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_id = (const gchar* (*) (PlankDocklet*)) docky_cpu_monitor_docklet_real_get_id;
	iface->get_name = (const gchar* (*) (PlankDocklet*)) docky_cpu_monitor_docklet_real_get_name;
	iface->get_description = (const gchar* (*) (PlankDocklet*)) docky_cpu_monitor_docklet_real_get_description;
	iface->get_icon = (const gchar* (*) (PlankDocklet*)) docky_cpu_monitor_docklet_real_get_icon;
	iface->is_supported = (gboolean (*) (PlankDocklet*)) docky_cpu_monitor_docklet_real_is_supported;
	iface->make_element = (PlankDockElement* (*) (PlankDocklet*, const gchar*, GFile*)) docky_cpu_monitor_docklet_real_make_element;
}

static void
docky_cpu_monitor_docklet_instance_init (DockyCPUMonitorDocklet * self,
                                         gpointer klass)
{
}

static GType
docky_cpu_monitor_docklet_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DockyCPUMonitorDockletClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) docky_cpu_monitor_docklet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DockyCPUMonitorDocklet), 0, (GInstanceInitFunc) docky_cpu_monitor_docklet_instance_init, NULL };
	static const GInterfaceInfo plank_docklet_info = { (GInterfaceInitFunc) docky_cpu_monitor_docklet_plank_docklet_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType docky_cpu_monitor_docklet_type_id;
	docky_cpu_monitor_docklet_type_id = g_type_register_static (G_TYPE_OBJECT, "DockyCPUMonitorDocklet", &g_define_type_info, 0);
	g_type_add_interface_static (docky_cpu_monitor_docklet_type_id, PLANK_TYPE_DOCKLET, &plank_docklet_info);
	return docky_cpu_monitor_docklet_type_id;
}

GType
docky_cpu_monitor_docklet_get_type (void)
{
	static volatile gsize docky_cpu_monitor_docklet_type_id__once = 0;
	if (g_once_init_enter (&docky_cpu_monitor_docklet_type_id__once)) {
		GType docky_cpu_monitor_docklet_type_id;
		docky_cpu_monitor_docklet_type_id = docky_cpu_monitor_docklet_get_type_once ();
		g_once_init_leave (&docky_cpu_monitor_docklet_type_id__once, docky_cpu_monitor_docklet_type_id);
	}
	return docky_cpu_monitor_docklet_type_id__once;
}

